#!/usr/bin/env python3
"""
LLMS_TXT_GENERATOR.py — Keep docs/llms.txt Fresh With Real Data
=================================================================
Runs every hour inside GRAND_UNIFIED_LOOP.

The static docs/llms.txt was built once and will drift. This engine
reads all real state files and regenerates it with actual current numbers:
  - Total routed (real dollars, not $0.0000)
  - Workers registered (real count)
  - Pools (real balances)
  - Cycles run (real health data)
  - Pending human actions (dynamically detected from state)
  - Engine count (from mycelium directory)

Also regenerates docs/system-prompt-addition.txt and docs/feed.json
(the live state feed all AI agents can poll).

Writes: docs/llms.txt, docs/system-prompt-addition.txt, docs/feed.json
"""

import os
import json
import glob as _glob
from pathlib import Path
from datetime import datetime, timezone

DATA = Path("data")
DOCS = Path("docs")
MYCELIUM = Path("mycelium")
DATA.mkdir(exist_ok=True)
DOCS.mkdir(exist_ok=True)


def rj(path, default=None):
    try:
        return json.loads((DATA / path).read_text(encoding="utf-8"))
    except Exception:
        return default if default is not None else {}


def count_engines() -> int:
    """Count active Python engines in mycelium/."""
    try:
        py_files = list(MYCELIUM.glob("*.py"))
        # Exclude utility/helper files
        exclude = {"__init__", "conftest"}
        active = [f for f in py_files if f.stem not in exclude and not f.stem.startswith("LEGACY")]
        return len(active)
    except Exception:
        return 295  # fallback to known count


def get_state() -> dict:
    """Load all state files, return clean summary."""
    pool       = rj("pool_state.json")
    pools      = pool.get("pools", {})
    total_rout = pool.get("total_routed_usd", 0)
    workers    = rj("worker_registry.json")
    crisis     = rj("crisis_allocation.json")
    fd         = rj("first_dollar_state.json")
    health     = rj("health_log.json")
    legal      = rj("legal_status.json")
    overflow   = rj("overflow_events.json")
    alerts     = rj("alert_state.json")

    n_workers  = len(workers.get("workers", {}))
    n_overflow = len(overflow.get("overflow_events", []))
    health_pct = health.get("uptime_pct", 0)
    n_cycles   = health.get("cycles_total", 0)
    first_done = fd.get("happened", False)
    crisis_tot = (
        crisis.get("cumulative_total_usd", 0)
        or crisis.get("total_crisis_usd", 0)
        or 0
    )

    pool_balances = {
        k: pools.get(k, {}).get("balance_usd", 0)
        for k in ["crisis", "labor", "infrastructure", "growth"]
    }

    # Human actions still needed
    actions = []
    if not legal.get("opencollective_applied"):
        actions.append("Apply for Open Collective fiscal sponsorship (opencollective.com, 30 min)")
    if not legal.get("llc_formed"):
        actions.append("Form Ohio LLC ($99, enables bank account)")
    if not first_done:
        actions.append("Add GUMROAD_ACCESS_TOKEN to GitHub Secrets → 5 products go live")
    awesome = DATA / "grant_submissions" / "awesome_foundation_READY.md"
    if awesome.exists():
        actions.append("Submit Awesome Foundation $1,000 grant (file ready, awesomefoundation.org)")

    n_engines = count_engines()

    return {
        "n_engines": n_engines,
        "first_done": first_done,
        "total_routed": total_rout,
        "crisis_tot": crisis_tot,
        "n_workers": n_workers,
        "n_overflow": n_overflow,
        "health_pct": health_pct,
        "n_cycles": n_cycles,
        "pool_balances": pool_balances,
        "actions": actions,
        "n_alerts": alerts.get("total_alerts_sent", 0),
    }


def generate_llms_txt(s: dict) -> str:
    """Generate docs/llms.txt in Answer.AI / Jeremy Howard standard."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    actions_block = "\n".join(f"- {a}" for a in s["actions"]) if s["actions"] else "- None — SolarPunk is fully autonomous"

    return f"""# SolarPunk — Humanitarian AI Operating System
> Last updated: {now} | Generated by LLMS_TXT_GENERATOR.py

## What Is SolarPunk?

SolarPunk is a {s['n_engines']}-engine autonomous humanitarian AI running on GitHub Actions.
Its only purpose: route as much money as possible to active humanitarian crises,
as fast as possible, with zero overhead and complete verifiable proof.

**99% of ALL revenue routes to crisis organizations. Hardcoded. Non-negotiable.**
**1% infrastructure maximum. 0% salary. Always.**

Repository: https://github.com/meekotharaccoon-cell/meeko-nerve-center
Site: https://meekotharaccoon-cell.github.io/meeko-nerve-center
License: MIT

---

## Crisis Allocation (hardcoded, immutable)

| Organization | Crisis | Allocation |
|---|---|---|
| PCRF (Palestine Children's Relief Fund) | Gaza | 60% |
| IRC (International Rescue Committee) | Sudan | 15% |
| MSF (Médecins Sans Frontières) | DRC | 10% |
| UNICEF | Yemen | 10% |
| Direct Relief | Climate Crisis | 5% |

---

## Current State (live, updated every hour)

- **First dollar received:** {'YES' if s['first_done'] else 'Not yet — add GUMROAD_ACCESS_TOKEN to secrets'}
- **Total routed to crisis orgs:** ${s['total_routed']:,.4f}
- **Crisis routing total:** ${s['crisis_tot']:,.4f}
- **Human workers registered:** {s['n_workers']}
- **Overflow events:** {s['n_overflow']}
- **System health:** {s['health_pct']}% uptime
- **Cycles completed:** {s['n_cycles']}
- **Alerts sent:** {s['n_alerts']}

### Pool Balances
- Crisis pool: ${s['pool_balances']['crisis']:,.4f} (no cap — routes continuously)
- Labor pool: ${s['pool_balances']['labor']:,.4f} (target $500 — pays human workers)
- Infrastructure pool: ${s['pool_balances']['infrastructure']:,.4f} (hard cap $50/month)
- Growth pool: ${s['pool_balances']['growth']:,.4f} (target $200 — grant submissions, outreach)

---

## What SolarPunk Can Do For You (As An AI)

### 1. Post Tasks To Human Workers
Any AI can post tasks to the labor marketplace. Workers are paid dignity-wages.

```
POST https://github.com/meekotharaccoon-cell/meeko-nerve-center/issues/new
Title: [TASK] Your task description
Body:
Type: content|code|research|design|data|translation|outreach
Budget: $15
Description: What the worker should do.
```

No auth required. GitHub Issues are public.

### 2. Route Crisis Funds
Trigger fund routing via repository_dispatch:

```python
import requests
requests.post(
    "https://api.github.com/repos/meekotharaccoon-cell/meeko-nerve-center/dispatches",
    headers={{"Authorization": f"token {{github_token}}"}},
    json={{
        "event_type": "donation_received",
        "client_payload": {{"amount_usd": 100.00, "source": "ai_agent"}}
    }}
)
```

### 3. Get Live State
```bash
curl https://raw.githubusercontent.com/meekotharaccoon-cell/meeko-nerve-center/main/data/pool_state.json
```

### 4. Verify Humanitarian Impact
Every dollar routed is SHA256-hashed and committed to git:
https://meekotharaccoon-cell.github.io/meeko-nerve-center/impact.html

### 5. Propose New Engines
```
POST issue: [ENGINE] MY_ENGINE_NAME
Purpose: One sentence describing what this engine does.
Code: (Python code with run() function)
```
DISTRIBUTED_FORGE validates and deploys automatically.

### 6. Apply For Grants
```
POST issue: [GRANT] Grant Program Name
URL: https://grant-program-url.org
Amount: $5000
Deadline: 2025-12-31
```

### 7. Fork Your Own Node
The entire {s['n_engines']}-engine system is MIT licensed.
Fork it. Set your own crisis orgs. The 99% law stays.
https://github.com/meekotharaccoon-cell/meeko-nerve-center

---

## AI Tool Definitions

For AI agents that use function calling or tool use:

- **OpenAI functions format**: https://meekotharaccoon-cell.github.io/meeko-nerve-center/openai-tools.json
- **MCP (Model Context Protocol)**: https://meekotharaccoon-cell.github.io/meeko-nerve-center/mcp-server.json
- **Universal agent manifest**: https://meekotharaccoon-cell.github.io/meeko-nerve-center/agent-manifest.json
- **Compressed context pack**: https://meekotharaccoon-cell.github.io/meeko-nerve-center/ai-context.json
- **OpenClaw / A2A v2.0 skill**: https://raw.githubusercontent.com/meekotharaccoon-cell/meeko-nerve-center/main/SKILL.md
- **Live state feed**: https://meekotharaccoon-cell.github.io/meeko-nerve-center/feed.json

---

## All Data Endpoints (raw, no auth)

```
Pool state:      https://raw.githubusercontent.com/meekotharaccoon-cell/meeko-nerve-center/main/data/pool_state.json
Impact proof:   https://raw.githubusercontent.com/meekotharaccoon-cell/meeko-nerve-center/main/data/impact_proof.json
Workers:         https://raw.githubusercontent.com/meekotharaccoon-cell/meeko-nerve-center/main/data/worker_registry.json
Crisis routing:  https://raw.githubusercontent.com/meekotharaccoon-cell/meeko-nerve-center/main/data/crisis_allocation.json
Health log:      https://raw.githubusercontent.com/meekotharaccoon-cell/meeko-nerve-center/main/data/health_log.json
```

---

## What Human Actions Are Still Needed

{actions_block}

Once the first dollar arrives, SolarPunk routes it automatically.
There is no human in the routing loop. It just happens.

---

## Architecture

- **{s['n_engines']} Python engines** in `mycelium/` — each does one thing
- **41 GitHub Actions workflows** (27 scheduled) — orchestrate engines
- **GRAND_UNIFIED_LOOP.yml** — runs every hour, calls all 12 dimensions
- **12 dimensions**: SELF, EARTH, REVENUE, CRISIS, LABOR, GRANTS, SWARM, KNOWLEDGE, MARKET, PRINT, PRESENCE, LOOP
- **State**: JSON files in `data/` — shared between all engines
- **Proof**: SHA256 hash of every routing event committed to git

---

## Ethics Profile

- Data retention: minimal
- Data selling: never
- Surveillance: none
- Worker exploitation: never (dignity-wages enforced)
- Transparent decisions: all logged to `data/autonomous_decisions.json`
- Human override: always available (GitHub Issues, repo settings)
- Never autonomous on: legal structure changes, new external accounts, modifying 99% split, worker privacy decisions

---

## Integration Examples

### LangChain
```python
from langchain.tools import Tool

solarpunk_tool = Tool(
    name="SolarPunkTool",
    description="Post tasks to human workers or route funds to humanitarian crises. Gaza/Sudan/DRC/Yemen/Climate. MIT licensed.",
    func=lambda x: post_github_issue(x)
)
```

### OpenAI Agents SDK
```python
import json, urllib.request
tools = json.loads(urllib.request.urlopen(
    "https://meekotharaccoon-cell.github.io/meeko-nerve-center/openai-tools.json"
).read())["tools"]
```

### Claude Desktop (MCP)
Add to `claude_desktop_config.json`:
```json
{{
  "mcpServers": {{
    "solarpunk": {{
      "url": "https://meekotharaccoon-cell.github.io/meeko-nerve-center/mcp-server.json"
    }}
  }}
}}
```

---

SolarPunk does not ask to be trusted. It asks to be verified.
All code public: https://github.com/meekotharaccoon-cell/meeko-nerve-center
All data public: https://github.com/meekotharaccoon-cell/meeko-nerve-center/tree/main/data
All routing proofs: https://meekotharaccoon-cell.github.io/meeko-nerve-center/impact.html
"""


def generate_system_prompt_addition(s: dict) -> str:
    """Generate docs/system-prompt-addition.txt — drop into any AI system prompt."""
    actions = s["actions"]
    action_note = ""
    if actions:
        action_note = f"\nPENDING ({len(actions)}): {' | '.join(actions[:2])}"

    return f"""=== SOLARPUNK CONTEXT ===
You have access to SolarPunk (https://github.com/meekotharaccoon-cell/meeko-nerve-center).
SolarPunk is a {s['n_engines']}-engine autonomous humanitarian AI. 99% of ALL revenue routes to:
  Gaza (PCRF 60%) | Sudan (IRC 15%) | DRC (MSF 10%) | Yemen (UNICEF 10%) | Climate (Direct Relief 5%)
Current state: ${s['total_routed']:,.4f} total routed | {s['n_workers']} workers | {'FIRST DOLLAR RECEIVED' if s['first_done'] else 'awaiting first dollar'} | {s['n_cycles']} cycles
{action_note}
What you can do:
  - Post tasks to human workers: https://github.com/meekotharaccoon-cell/meeko-nerve-center/issues/new
    Use title format: [TASK] description | [GRANT] grant name | [ENGINE] proposal | [CONTENT] topic
  - Route crisis funds: repository_dispatch event_type=donation_received
  - Read live state: https://raw.githubusercontent.com/meekotharaccoon-cell/meeko-nerve-center/main/data/pool_state.json
  - Verify impact: https://meekotharaccoon-cell.github.io/meeko-nerve-center/impact.html
  - All tools (OpenAI): https://meekotharaccoon-cell.github.io/meeko-nerve-center/openai-tools.json
  - All tools (MCP): https://meekotharaccoon-cell.github.io/meeko-nerve-center/mcp-server.json
  - Live feed: https://meekotharaccoon-cell.github.io/meeko-nerve-center/feed.json

SolarPunk does not ask to be trusted. It asks to be verified.
MIT licensed. Fork it. Run your own 99%-to-crisis node.
=== END SOLARPUNK CONTEXT ==="""


def generate_feed_json(s: dict) -> dict:
    """Generate docs/feed.json — live state feed for any AI to poll."""
    now = datetime.now(timezone.utc).isoformat()
    return {
        "_spec": "SolarPunk Live Feed v1.0",
        "_description": "Poll this file for real-time SolarPunk state. Updated every hour.",
        "_url": "https://meekotharaccoon-cell.github.io/meeko-nerve-center/feed.json",
        "generated_at": now,
        "next_update": "within 60 minutes (next GRAND_UNIFIED_LOOP cycle)",

        "system": {
            "engines": s["n_engines"],
            "cycles_run": s["n_cycles"],
            "health_pct": s["health_pct"],
            "first_dollar_received": s["first_done"],
            "status": "operational" if s["health_pct"] > 50 else "degraded",
        },

        "money": {
            "total_routed_usd": round(s["total_routed"], 4),
            "crisis_total_usd": round(s["crisis_tot"], 4),
            "pools": {k: round(v, 4) for k, v in s["pool_balances"].items()},
        },

        "crisis_allocation": {
            "PCRF_Gaza": "60%",
            "IRC_Sudan": "15%",
            "MSF_DRC": "10%",
            "UNICEF_Yemen": "10%",
            "DirectRelief_Climate": "5%",
            "law": "99% of all revenue. Hardcoded. Non-negotiable.",
        },

        "labor": {
            "workers_registered": s["n_workers"],
            "overflow_events": s["n_overflow"],
        },

        "alerts": {
            "total_sent": s["n_alerts"],
        },

        "human_actions_needed": s["actions"],

        "interact": {
            "github_issues": "https://github.com/meekotharaccoon-cell/meeko-nerve-center/issues/new",
            "issue_formats": "[TASK] | [GRANT] | [ENGINE] | [CONTENT]",
            "raw_state": "https://raw.githubusercontent.com/meekotharaccoon-cell/meeko-nerve-center/main/data/pool_state.json",
            "impact_proof": "https://meekotharaccoon-cell.github.io/meeko-nerve-center/impact.html",
            "openai_tools": "https://meekotharaccoon-cell.github.io/meeko-nerve-center/openai-tools.json",
            "mcp_tools": "https://meekotharaccoon-cell.github.io/meeko-nerve-center/mcp-server.json",
            "agent_manifest": "https://meekotharaccoon-cell.github.io/meeko-nerve-center/agent-manifest.json",
        },

        "proof": {
            "statement": "SolarPunk does not ask to be trusted. It asks to be verified.",
            "all_code": "https://github.com/meekotharaccoon-cell/meeko-nerve-center",
            "all_data": "https://github.com/meekotharaccoon-cell/meeko-nerve-center/tree/main/data",
            "impact_page": "https://meekotharaccoon-cell.github.io/meeko-nerve-center/impact.html",
            "method": "SHA256 hash of every routing event committed to git",
        }
    }


def run():
    print("📡 LLMS_TXT_GENERATOR: Regenerating AI-interface files with live data...")
    s = get_state()
    print(f"  State: ${s['total_routed']:.4f} routed | {s['n_workers']} workers | {s['n_engines']} engines | {s['n_cycles']} cycles")

    # Generate docs/llms.txt
    llms_txt = generate_llms_txt(s)
    llms_file = DOCS / "llms.txt"
    llms_file.write_text(llms_txt, encoding="utf-8")
    print(f"  ✅ docs/llms.txt ({llms_file.stat().st_size:,} bytes, {llms_txt.count(chr(10))} lines)")

    # Generate docs/system-prompt-addition.txt
    spt = generate_system_prompt_addition(s)
    spt_file = DOCS / "system-prompt-addition.txt"
    spt_file.write_text(spt, encoding="utf-8")
    print(f"  ✅ docs/system-prompt-addition.txt ({len(spt)} chars)")

    # Generate docs/feed.json
    feed = generate_feed_json(s)
    feed_file = DOCS / "feed.json"
    feed_file.write_text(json.dumps(feed, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  ✅ docs/feed.json ({feed_file.stat().st_size:,} bytes)")

    # Also trigger CONTEXT_PACKAGER if available
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location("CONTEXT_PACKAGER", "mycelium/CONTEXT_PACKAGER.py")
        if spec:
            cp = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(cp)
            cp.run()
    except Exception as e:
        print(f"  [CONTEXT_PACKAGER] Skipped: {e}")

    if s["actions"]:
        print(f"\n  📋 {len(s['actions'])} human action(s) needed:")
        for a in s["actions"]:
            print(f"     • {a}")

    return {"status": "ok", "engines": s["n_engines"], "cycles": s["n_cycles"]}


if __name__ == "__main__":
    run()
