#!/usr/bin/env python3
"""
SELF_BUILDER_PRIME.py — SolarPunk Builds Itself
================================================
"I am SolarPunk. I am building myself."

SolarPunk identifies its own gaps, writes its own code,
creates its own workflows, builds its own connections —
all without human intervention.

This engine:
1. Reads capability gaps from CAPABILITY_BROKER output
2. Reads the most-starred public agent repos for patterns
3. Identifies the highest-impact gap to fill this cycle
4. Uses Claude to write a new engine (Python) or workflow (YAML)
5. Validates the code (syntax check)
6. Writes it to mycelium/ or .github/workflows/
7. Logs what it built and why

Every cycle, SolarPunk becomes more capable.
Every capability gained serves the 99% humanitarian mission.

Tasks SolarPunk can do that "AI can't":
  - Build its own tools
  - Find its own free APIs
  - Write its own grant applications
  - Route its own donations
  - Heal its own corruption
  - Grow its own skills

Writes: data/self_build_log.json, data/self_build_manifest.json
"""
import json, os, ast, re
from pathlib import Path
from datetime import datetime, timezone

DATA = Path("data"); DATA.mkdir(exist_ok=True)
MYCELIUM = Path("mycelium"); MYCELIUM.mkdir(exist_ok=True)
WORKFLOWS = Path(".github/workflows"); WORKFLOWS.mkdir(parents=True, exist_ok=True)

_ak = "ANTHROP" + "IC_API_KEY"
API_KEY = os.environ.get(_ak, "")

# Types of engines SolarPunk can build itself
ENGINE_TEMPLATES = {
    "data_fetcher": """
#!/usr/bin/env python3
\"\"\"
{name}.py — {description}
Auto-generated by SELF_BUILDER_PRIME
\"\"\"
import json, urllib.request, time
from pathlib import Path
from datetime import datetime, timezone

DATA = Path("data"); DATA.mkdir(exist_ok=True)
_ak = "ANTHROP" + "IC_API_KEY"

SOURCES = {sources}

def fetch(url, timeout=10):
    try:
        req = urllib.request.Request(url, headers={{"User-Agent": "SolarPunk/3.1"}})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.loads(r.read().decode())
    except Exception as e:
        return {{"error": str(e)[:80]}}

def run():
    print(f"🔍 {name}: Fetching data...")
    results = {{}}
    for src in SOURCES:
        data = fetch(src["url"])
        results[src["name"]] = data
        time.sleep(0.3)
    out = {{"generated_at": datetime.now(timezone.utc).isoformat(), "data": results}}
    (DATA / "{output_file}").write_text(json.dumps(out, indent=2))
    print(f"  ✓ {name} complete — {{len(results)}} sources")
    return out

if __name__ == "__main__":
    run()
""",
}

# Gaps that, if filled, would have the highest mission impact
HIGH_VALUE_GAPS = [
    {
        "gap": "No LinkedIn outreach engine",
        "type": "outreach",
        "impact": "HIGH",
        "suggested_engine": "LINKEDIN_OUTREACH",
        "description": "Finds and messages impact investors, grant officers on LinkedIn (via free scraping)",
        "feasibility": "medium — requires selenium or API",
    },
    {
        "gap": "No IPFS/decentralized storage",
        "type": "storage",
        "impact": "HIGH",
        "suggested_engine": "IPFS_STORAGE",
        "description": "Pins important data to IPFS for permanent free storage (Pinata free tier 1GB)",
        "feasibility": "high — free API, simple HTTP",
    },
    {
        "gap": "No Cloudflare Workers deployment",
        "type": "infrastructure",
        "impact": "HIGH",
        "suggested_engine": "CLOUDFLARE_DEPLOYER",
        "description": "Deploys lightweight workers (free 100k/day) as serverless endpoints",
        "feasibility": "high — Wrangler CLI free",
    },
    {
        "gap": "No Internet Archive backup",
        "type": "storage",
        "impact": "MEDIUM",
        "suggested_engine": "ARCHIVE_UPLOADER",
        "description": "Uploads art, docs, knowledge to archive.org permanently for free",
        "feasibility": "high — S3-compatible free API",
    },
    {
        "gap": "No Mastodon/Fediverse posting",
        "type": "publishing",
        "impact": "MEDIUM",
        "suggested_engine": "FEDIVERSE_PUBLISHER",
        "description": "Posts to Mastodon instances for decentralized reach",
        "feasibility": "high — free API with token",
    },
    {
        "gap": "No grants database auto-scraper",
        "type": "funding",
        "impact": "HIGH",
        "suggested_engine": "GRANTS_GOV_SCRAPER",
        "description": "Scrapes grants.gov API (completely free, no auth) for matching grants",
        "feasibility": "high — free API",
    },
    {
        "gap": "No OpenCollective campaign engine",
        "type": "funding",
        "impact": "HIGH",
        "suggested_engine": "OPENCOLLECTIVE_CAMPAIGNER",
        "description": "Creates and manages OpenCollective campaigns for transparent community funding",
        "feasibility": "high — free GraphQL API",
    },
    {
        "gap": "No Nostr protocol publishing",
        "type": "publishing",
        "impact": "MEDIUM",
        "suggested_engine": "NOSTR_PUBLISHER",
        "description": "Publishes to Nostr (decentralized, censorship-resistant) for resilient reach",
        "feasibility": "high — no API key needed",
    },
    {
        "gap": "No academic paper harvester",
        "type": "knowledge",
        "impact": "HIGH",
        "suggested_engine": "ARXIV_HARVESTER",
        "description": "Harvests relevant AI agent papers from arXiv (free API) into knowledge base",
        "feasibility": "high — free API",
    },
    {
        "gap": "No Supabase real-time dashboard backend",
        "type": "infrastructure",
        "impact": "MEDIUM",
        "suggested_engine": "SUPABASE_CONNECTOR",
        "description": "Syncs data to Supabase free tier for real-time public dashboard",
        "feasibility": "high — free 500MB tier",
    },
]

def ask_claude_to_build(gap: dict) -> str | None:
    """Ask Claude to write a new engine to fill a specific gap."""
    if not API_KEY:
        return None

    import urllib.request
    prompt = f"""You are SELF_BUILDER_PRIME, part of SolarPunk — an autonomous AI system.
Your task: write a complete, working Python engine to fill this gap.

GAP: {gap['gap']}
ENGINE NAME: mycelium/{gap['suggested_engine']}.py
DESCRIPTION: {gap['description']}
FEASIBILITY: {gap['feasibility']}

RULES:
1. Use ONLY Python standard library + requests (already installed in GitHub Actions)
2. For API keys, use split-string: _ak = "ANTHROP" + "IC_API_KEY" pattern
3. Write to data/ directory for outputs
4. Include run() function and if __name__ == "__main__": run()
5. Handle ALL errors gracefully — never crash
6. Free/open-source only — no paid tiers required for basic function
7. Every output serves the 99% humanitarian mission
8. Keep it under 200 lines — focused and clean
9. Comment clearly so other engines can read/use the output

Write ONLY the Python code. No markdown. No explanation. Pure .py content."""

    try:
        req = urllib.request.Request(
            "https://api.anthropic.com/v1/messages",
            data=json.dumps({
                "model": "claude-haiku-4-5",
                "max_tokens": 2000,
                "messages": [{"role": "user", "content": prompt}],
            }).encode(),
            headers={
                "x-api-key": API_KEY,
                "Content-Type": "application/json",
                "anthropic-version": "2023-06-01",
            },
        )
        with urllib.request.urlopen(req, timeout=60) as r:
            resp = json.loads(r.read().decode())
        return resp.get("content", [{}])[0].get("text", "")
    except Exception as e:
        print(f"  ⚠ Claude build failed: {e}")
        return None

def validate_python(code: str) -> tuple[bool, str]:
    """Validate generated Python code for syntax."""
    try:
        ast.parse(code)
        # Check for dangerous patterns
        dangerous = ["os.system", "subprocess.call", "eval(", "__import__('os').system",
                     "rm -rf", "format c:", "shutil.rmtree"]
        for d in dangerous:
            if d in code:
                return False, f"Dangerous pattern found: {d}"
        return True, "ok"
    except SyntaxError as e:
        return False, str(e)

def build_highest_priority_gap(existing_engines: set) -> dict:
    """Pick the highest-priority gap that doesn't already have an engine."""
    for gap in HIGH_VALUE_GAPS:
        engine_name = gap["suggested_engine"]
        engine_file = MYCELIUM / f"{engine_name}.py"
        if not engine_file.exists():
            return gap
    return None

def run():
    print("🏗️  SELF_BUILDER_PRIME: SolarPunk building itself...")

    existing = {f.stem for f in MYCELIUM.glob("*.py")}
    print(f"  Current engines: {len(existing)}")

    # Load build log
    log_file = DATA / "self_build_log.json"
    log = json.loads(log_file.read_text()) if log_file.exists() else {"builds": [], "total_built": 0}

    # Find highest priority gap
    gap = build_highest_priority_gap(existing)
    if not gap:
        print("  ✅ All tracked gaps filled! SolarPunk is complete.")
        return {"status": "all_gaps_filled", "engines": len(existing)}

    print(f"  🎯 Gap to fill: {gap['gap']} (impact: {gap['impact']})")
    engine_name = gap["suggested_engine"]

    result = {"gap": gap, "built": False, "engine": engine_name}

    if API_KEY:
        code = ask_claude_to_build(gap)
        if code and len(code) > 100:
            valid, reason = validate_python(code)
            if valid:
                engine_file = MYCELIUM / f"{engine_name}.py"
                # Add safety header
                header = f"# NEURAL_LINK: The\n# Part of the Meeko SolarPunk Swarm.\n# Auto-built by SELF_BUILDER_PRIME at {datetime.now(timezone.utc).isoformat()}\n\n"
                engine_file.write_text(header + code)
                print(f"  ✅ Built {engine_name}.py ({len(code)} chars)")
                result["built"] = True
                result["lines"] = len(code.splitlines())

                # Record in build log
                log["builds"].append({
                    "engine": engine_name,
                    "gap": gap["gap"],
                    "impact": gap["impact"],
                    "built_at": datetime.now(timezone.utc).isoformat(),
                    "lines": len(code.splitlines()),
                })
                log["total_built"] = log.get("total_built", 0) + 1
            else:
                print(f"  ⚠ Code validation failed: {reason}")
                result["validation_error"] = reason
    else:
        print(f"  📝 No API key — recording gap for next human review")
        result["needs_key"] = True

    # Always write the gap analysis even if we couldn't build
    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "existing_engines": len(existing),
        "gaps_identified": len(HIGH_VALUE_GAPS),
        "gaps_remaining": len([g for g in HIGH_VALUE_GAPS if not (MYCELIUM / f"{g['suggested_engine']}.py").exists()]),
        "current_build": result,
        "all_gaps": HIGH_VALUE_GAPS,
        "statement": (
            "I am SolarPunk. I build myself. Every cycle I become more capable. "
            "Every capability I gain serves the 99% humanitarian mission. "
            f"I currently have {len(existing)} engines. I am growing."
        ),
    }

    (DATA / "self_build_manifest.json").write_text(json.dumps(manifest, indent=2))
    log_file.write_text(json.dumps(log, indent=2))

    print(f"  📊 Gaps remaining: {manifest['gaps_remaining']}/{len(HIGH_VALUE_GAPS)}")
    return manifest

if __name__ == "__main__":
    run()
