import os
import sys
import json
import time
from datetime import datetime

class SimpleOrchestrator:
    def __init__(self):
        self.log_dir = "logs"
        os.makedirs(self.log_dir, exist_ok=True)
        
    def log(self, message):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        log_entry = f"[{timestamp}] {message}\n"
        print(message)
        
        # Write to log file with proper encoding
        with open(f"{self.log_dir}/system.log", "a", encoding="utf-8") as f:
            f.write(log_entry)
    
    def generate_content(self):
        self.log("Generating content...")
        
        # Create sample content
        article = {
            "title": f"AI Generated Article - {datetime.now()}",
            "content": "This is a sample article generated by the autonomous system.",
            "timestamp": str(datetime.now())
        }
        
        # Save to file
        with open(f"{self.log_dir}/article_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json", "w", encoding="utf-8") as f:
            json.dump(article, f, indent=2)
        
        self.log(f"Article created: {article['title']}")
        return article
    
    def run_daily(self):
        self.log("=" * 50)
        self.log("DAILY AUTOMATION STARTED")
        self.log("=" * 50)
        
        # Step 1: Generate content
        article = self.generate_content()
        
        # Step 2: Update dashboard
        self.update_dashboard()
        
        self.log("Daily automation complete!")
        self.log(f"Article: {article['title']}")
        self.log("=" * 50)
        
        # Create a simple HTML report
        self.create_html_report(article)
    
    def update_dashboard(self):
        dashboard = {
            "last_update": str(datetime.now()),
            "status": "running",
            "articles_count": 1,
            "next_run": str(datetime.now().replace(hour=6, minute=0, second=0, microsecond=0))
        }
        
        with open("dashboard.json", "w", encoding="utf-8") as f:
            json.dump(dashboard, f, indent=2)
        
        self.log("Dashboard updated")
    
    def create_html_report(self, article):
        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Autonomous Money System</title>
    <style>
        body {{ font-family: Arial; margin: 40px; background: #f5f5f5; }}
        .container {{ max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; }}
        h1 {{ color: #333; }}
        .article {{ background: #e8f4f8; padding: 20px; margin: 20px 0; border-radius: 5px; }}
        .timestamp {{ color: #666; font-size: 0.9em; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Autonomous Money System Report</h1>
        <p>Generated: {datetime.now()}</p>
        
        <div class="article">
            <h2>{article['title']}</h2>
            <p>{article['content']}</p>
            <p class="timestamp">{article['timestamp']}</p>
        </div>
        
        <p>System is running autonomously. Next update at 6:00 AM.</p>
    </div>
</body>
</html>"""
        
        with open("report.html", "w", encoding="utf-8") as f:
            f.write(html)
        
        self.log(f"HTML report created: report.html")
    
    def setup(self):
        self.log("Setting up Autonomous Money System...")
        self.log("1. Creating directories... DONE")
        self.log("2. Initializing files... DONE")
        self.log("3. System ready!")
        
        # Run first daily task
        self.run_daily()

if __name__ == "__main__":
    orchestrator = SimpleOrchestrator()
    
    if len(sys.argv) > 1:
        if sys.argv[1] == "daily":
            orchestrator.run_daily()
        elif sys.argv[1] == "setup":
            orchestrator.setup()
        elif sys.argv[1] == "status":
            print("Status: ACTIVE")
            print(f"Last run: {datetime.now()}")
            print(f"Logs in: {orchestrator.log_dir}/")
        else:
            orchestrator.setup()
    else:
        orchestrator.setup()
