# NEURAL_LINK: The
# Part of the Meeko SolarPunk Swarm.

#!/usr/bin/env python3
"""
MICRO_PRODUCT_FACTORY.py -- Instant micro digital product generator
====================================================================
Generates markdown template packs across 4 domains in seconds.
Each template is a ready-to-use code snippet or config with comments.
Outputs ~40-50 template files and a manifest per domain.

Domains:
  python-automation   -- web scraping, file processing, API calls, etc.
  github-actions      -- CI/CD, auto-deploy, scheduled tasks, etc.
  ai-prompts          -- system prompts, chain-of-thought, JSON output, etc.
  solarpunk-configs   -- engine templates, OMNIBUS configs, wire patterns

Output:
  products/templates/{domain}/*.md
  products/templates/{domain}/manifest.json
  data/micro_product_factory_report.json
"""
import json
from pathlib import Path
from datetime import datetime, timezone

# -- paths ----------------------------------------------------------------
BASE = Path(__file__).resolve().parent.parent
DATA = BASE / "data"
DATA.mkdir(exist_ok=True)
PRODUCTS = BASE / "products" / "templates"
PRODUCTS.mkdir(parents=True, exist_ok=True)
REPORT_FILE = DATA / "micro_product_factory_report.json"


def load_json(path):
    """Load JSON from path, return empty dict on failure."""
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except Exception:
        return {}


def save_json(path, data):
    """Write data as JSON to path."""
    Path(path).write_text(
        json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8"
    )


# -- template definitions -------------------------------------------------

PYTHON_AUTOMATION_TEMPLATES = [
    {
        "filename": "web_scraper_requests.md",
        "title": "Web Scraper with Requests + BeautifulSoup",
        "content": "\n".join([
            "# Web Scraper with Requests + BeautifulSoup",
            "",
            "A minimal, production-ready web scraper.",
            "",
            "```python",
            "import requests",
            "from bs4 import BeautifulSoup",
            "import json, time",
            "",
            "def scrape_page(url, selector='article'):",
            '    """Fetch a page and extract elements by CSS selector."""',
            "    headers = {'User-Agent': 'Mozilla/5.0 (compatible; SolarPunkBot/1.0)'}",
            "    resp = requests.get(url, headers=headers, timeout=15)",
            "    resp.raise_for_status()",
            "    soup = BeautifulSoup(resp.text, 'html.parser')",
            "    return [el.get_text(strip=True) for el in soup.select(selector)]",
            "",
            "def scrape_multiple(urls, selector='article', delay=1.0):",
            '    """Scrape multiple URLs with polite delay."""',
            "    results = {}",
            "    for url in urls:",
            "        try:",
            "            results[url] = scrape_page(url, selector)",
            "            time.sleep(delay)",
            "        except Exception as e:",
            "            results[url] = {'error': str(e)}",
            "    return results",
            "",
            "if __name__ == '__main__':",
            "    urls = ['https://example.com']",
            "    data = scrape_multiple(urls, selector='h1')",
            "    print(json.dumps(data, indent=2))",
            "```",
            "",
            "## Usage",
            "- Change `selector` to target specific HTML elements",
            "- Adjust `delay` to be respectful to servers",
            "- Add proxy rotation for large-scale scraping",
        ]),
    },
    {
        "filename": "file_processor_csv.md",
        "title": "CSV File Processor Pipeline",
        "content": "\n".join([
            "# CSV File Processor Pipeline",
            "",
            "Batch process CSV files with filtering, transformation, and output.",
            "",
            "```python",
            "import csv, json",
            "from pathlib import Path",
            "",
            "def process_csv(input_path, output_path, transform_fn=None, filter_fn=None):",
            '    """Process a CSV: filter rows, transform columns, write output."""',
            "    rows = []",
            "    with open(input_path, 'r', newline='', encoding='utf-8') as f:",
            "        reader = csv.DictReader(f)",
            "        for row in reader:",
            "            if filter_fn and not filter_fn(row):",
            "                continue",
            "            if transform_fn:",
            "                row = transform_fn(row)",
            "            rows.append(row)",
            "",
            "    if not rows:",
            "        print('No rows matched filters.')",
            "        return 0",
            "",
            "    with open(output_path, 'w', newline='', encoding='utf-8') as f:",
            "        writer = csv.DictWriter(f, fieldnames=rows[0].keys())",
            "        writer.writeheader()",
            "        writer.writerows(rows)",
            "    return len(rows)",
            "",
            "# Example: keep rows where 'status' == 'active', uppercase names",
            "def my_filter(row):",
            "    return row.get('status') == 'active'",
            "",
            "def my_transform(row):",
            "    row['name'] = row.get('name', '').upper()",
            "    return row",
            "",
            "if __name__ == '__main__':",
            "    count = process_csv('input.csv', 'output.csv', my_transform, my_filter)",
            "    print('Processed %d rows' % count)",
            "```",
        ]),
    },
    {
        "filename": "api_client_rest.md",
        "title": "REST API Client with Retry Logic",
        "content": "\n".join([
            "# REST API Client with Retry Logic",
            "",
            "A reusable REST API client with exponential backoff.",
            "",
            "```python",
            "import requests, time, json",
            "",
            "class APIClient:",
            "    def __init__(self, base_url, api_key=None, max_retries=3):",
            "        self.base_url = base_url.rstrip('/')",
            "        self.session = requests.Session()",
            "        if api_key:",
            "            self.session.headers['Authorization'] = 'Bearer ' + api_key",
            "        self.max_retries = max_retries",
            "",
            "    def _request(self, method, endpoint, **kwargs):",
            "        url = self.base_url + '/' + endpoint.lstrip('/')",
            "        for attempt in range(self.max_retries):",
            "            try:",
            "                resp = self.session.request(method, url, timeout=30, **kwargs)",
            "                resp.raise_for_status()",
            "                return resp.json()",
            "            except requests.exceptions.RequestException as e:",
            "                if attempt == self.max_retries - 1:",
            "                    raise",
            "                wait = 2 ** attempt",
            "                print('Retry %d/%d in %ds: %s' % (attempt+1, self.max_retries, wait, e))",
            "                time.sleep(wait)",
            "",
            "    def get(self, endpoint, params=None):",
            "        return self._request('GET', endpoint, params=params)",
            "",
            "    def post(self, endpoint, data=None):",
            "        return self._request('POST', endpoint, json=data)",
            "",
            "if __name__ == '__main__':",
            "    client = APIClient('https://jsonplaceholder.typicode.com')",
            "    posts = client.get('/posts', params={'_limit': 5})",
            "    print(json.dumps(posts, indent=2))",
            "```",
        ]),
    },
    {
        "filename": "data_pipeline_etl.md",
        "title": "ETL Data Pipeline (Extract-Transform-Load)",
        "content": "\n".join([
            "# ETL Data Pipeline",
            "",
            "A lightweight extract-transform-load pipeline for JSON data.",
            "",
            "```python",
            "import json",
            "from pathlib import Path",
            "from datetime import datetime, timezone",
            "",
            "class ETLPipeline:",
            "    def __init__(self, name):",
            "        self.name = name",
            "        self.extracted = []",
            "        self.transformed = []",
            "        self.stats = {'extracted': 0, 'transformed': 0, 'loaded': 0, 'errors': 0}",
            "",
            "    def extract(self, source_path):",
            "        data = json.loads(Path(source_path).read_text(encoding='utf-8'))",
            "        if isinstance(data, list):",
            "            self.extracted = data",
            "        else:",
            "            self.extracted = [data]",
            "        self.stats['extracted'] = len(self.extracted)",
            "        return self",
            "",
            "    def transform(self, fn):",
            "        self.transformed = []",
            "        for record in self.extracted:",
            "            try:",
            "                result = fn(record)",
            "                if result is not None:",
            "                    self.transformed.append(result)",
            "            except Exception:",
            "                self.stats['errors'] += 1",
            "        self.stats['transformed'] = len(self.transformed)",
            "        return self",
            "",
            "    def load(self, dest_path):",
            "        output = {",
            "            'pipeline': self.name,",
            "            'timestamp': datetime.now(timezone.utc).isoformat(),",
            "            'stats': self.stats,",
            "            'data': self.transformed,",
            "        }",
            "        Path(dest_path).write_text(json.dumps(output, indent=2), encoding='utf-8')",
            "        self.stats['loaded'] = len(self.transformed)",
            "        return self.stats",
            "",
            "if __name__ == '__main__':",
            "    def enrich(rec):",
            "        rec['processed'] = True",
            "        return rec",
            "    pipe = ETLPipeline('demo')",
            "    # pipe.extract('input.json').transform(enrich).load('output.json')",
            "    print('ETL pipeline ready: %s' % pipe.name)",
            "```",
        ]),
    },
    {
        "filename": "cron_scheduler.md",
        "title": "Lightweight Cron Job Scheduler",
        "content": "\n".join([
            "# Lightweight Cron Job Scheduler",
            "",
            "Run Python functions on a schedule without external deps.",
            "",
            "```python",
            "import time, threading",
            "from datetime import datetime",
            "",
            "class CronJob:",
            "    def __init__(self, name, fn, interval_seconds=60):",
            "        self.name = name",
            "        self.fn = fn",
            "        self.interval = interval_seconds",
            "        self.running = False",
            "        self.run_count = 0",
            "",
            "    def start(self):",
            "        self.running = True",
            "        def loop():",
            "            while self.running:",
            "                try:",
            "                    self.fn()",
            "                    self.run_count += 1",
            "                    print('[%s] %s ran (count: %d)' % (datetime.now().isoformat(), self.name, self.run_count))",
            "                except Exception as e:",
            "                    print('[%s] %s error: %s' % (datetime.now().isoformat(), self.name, e))",
            "                time.sleep(self.interval)",
            "        t = threading.Thread(target=loop, daemon=True)",
            "        t.start()",
            "        return t",
            "",
            "    def stop(self):",
            "        self.running = False",
            "",
            "if __name__ == '__main__':",
            "    def heartbeat():",
            "        print('pulse')",
            "    job = CronJob('heartbeat', heartbeat, interval_seconds=5)",
            "    t = job.start()",
            "    time.sleep(16)  # Run for 16 seconds",
            "    job.stop()",
            "    print('Stopped after %d runs' % job.run_count)",
            "```",
        ]),
    },
    {
        "filename": "json_transformer.md",
        "title": "JSON Transformer Utility",
        "content": "\n".join([
            "# JSON Transformer Utility",
            "",
            "Flatten, filter, and reshape JSON data structures.",
            "",
            "```python",
            "import json",
            "from pathlib import Path",
            "",
            "def flatten_json(nested, prefix='', sep='.'):",
            '    """Flatten a nested dict into dot-notation keys."""',
            "    flat = {}",
            "    for key, val in nested.items():",
            "        new_key = prefix + sep + key if prefix else key",
            "        if isinstance(val, dict):",
            "            flat.update(flatten_json(val, new_key, sep))",
            "        elif isinstance(val, list):",
            "            for i, item in enumerate(val):",
            "                idx_key = '%s[%d]' % (new_key, i)",
            "                if isinstance(item, dict):",
            "                    flat.update(flatten_json(item, idx_key, sep))",
            "                else:",
            "                    flat[idx_key] = item",
            "        else:",
            "            flat[new_key] = val",
            "    return flat",
            "",
            "def pick_keys(data, keys):",
            '    """Extract only specified keys from a dict."""',
            "    return {k: data[k] for k in keys if k in data}",
            "",
            "if __name__ == '__main__':",
            "    sample = {'user': {'name': 'Meeko', 'tags': ['solarpunk', 'builder']}, 'score': 99}",
            "    print(json.dumps(flatten_json(sample), indent=2))",
            "```",
        ]),
    },
    {
        "filename": "file_watcher.md",
        "title": "Directory File Watcher",
        "content": "\n".join([
            "# Directory File Watcher",
            "",
            "Poll a directory for new or changed files and react.",
            "",
            "```python",
            "import time, os, json",
            "from pathlib import Path",
            "",
            "class FileWatcher:",
            "    def __init__(self, watch_dir, extensions=None):",
            "        self.watch_dir = Path(watch_dir)",
            "        self.extensions = extensions or ['*']",
            "        self.seen = {}",
            "",
            "    def scan(self):",
            "        changes = {'new': [], 'modified': []}",
            "        for ext in self.extensions:",
            "            pattern = '**/*.' + ext if ext != '*' else '**/*'",
            "            for p in self.watch_dir.glob(pattern):",
            "                if p.is_file():",
            "                    mtime = p.stat().st_mtime",
            "                    key = str(p)",
            "                    if key not in self.seen:",
            "                        changes['new'].append(key)",
            "                    elif self.seen[key] < mtime:",
            "                        changes['modified'].append(key)",
            "                    self.seen[key] = mtime",
            "        return changes",
            "",
            "    def watch(self, callback, interval=5):",
            "        print('Watching %s ...' % self.watch_dir)",
            "        while True:",
            "            changes = self.scan()",
            "            if changes['new'] or changes['modified']:",
            "                callback(changes)",
            "            time.sleep(interval)",
            "",
            "if __name__ == '__main__':",
            "    def on_change(changes):",
            "        print('Detected: %s' % json.dumps(changes, indent=2))",
            "    watcher = FileWatcher('.', extensions=['py', 'json'])",
            "    print('File watcher ready. %d extensions tracked.' % len(watcher.extensions))",
            "```",
        ]),
    },
    {
        "filename": "batch_renamer.md",
        "title": "Batch File Renamer",
        "content": "\n".join([
            "# Batch File Renamer",
            "",
            "Rename files in bulk using patterns and regex.",
            "",
            "```python",
            "import re, os",
            "from pathlib import Path",
            "",
            "def batch_rename(directory, pattern, replacement, dry_run=True):",
            '    """Rename files matching regex pattern."""',
            "    renamed = []",
            "    for f in Path(directory).iterdir():",
            "        if f.is_file():",
            "            new_name = re.sub(pattern, replacement, f.name)",
            "            if new_name != f.name:",
            "                new_path = f.parent / new_name",
            "                if dry_run:",
            "                    renamed.append(('%s -> %s' % (f.name, new_name)))",
            "                else:",
            "                    f.rename(new_path)",
            "                    renamed.append(('%s -> %s' % (f.name, new_name)))",
            "    return renamed",
            "",
            "if __name__ == '__main__':",
            "    # Example: remove 'copy_' prefix from files",
            "    results = batch_rename('.', r'^copy_', '', dry_run=True)",
            "    for r in results:",
            "        print('  ' + r)",
            "    print('Total: %d files (dry run)' % len(results))",
            "```",
        ]),
    },
]

GITHUB_ACTIONS_TEMPLATES = [
    {
        "filename": "ci_python_test.md",
        "title": "Python CI/CD Test Pipeline",
        "content": "\n".join([
            "# Python CI/CD Test Pipeline",
            "",
            "Run tests on every push with caching and matrix builds.",
            "",
            "```yaml",
            "name: Python CI",
            "on:",
            "  push:",
            "    branches: [main]",
            "  pull_request:",
            "    branches: [main]",
            "",
            "jobs:",
            "  test:",
            "    runs-on: ubuntu-latest",
            "    strategy:",
            "      matrix:",
            "        python-version: ['3.10', '3.11', '3.12']",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - name: Set up Python",
            "        uses: actions/setup-python@v5",
            "        with:",
            "          python-version: ${{ matrix.python-version }}",
            "          cache: pip",
            "      - name: Install dependencies",
            "        run: pip install -r requirements.txt",
            "      - name: Run tests",
            "        run: python -m pytest tests/ -v --tb=short",
            "      - name: Run linter",
            "        run: python -m flake8 . --count --show-source --statistics",
            "```",
        ]),
    },
    {
        "filename": "auto_deploy_pages.md",
        "title": "Auto Deploy to GitHub Pages",
        "content": "\n".join([
            "# Auto Deploy to GitHub Pages",
            "",
            "Deploy a static site on every push to main.",
            "",
            "```yaml",
            "name: Deploy to Pages",
            "on:",
            "  push:",
            "    branches: [main]",
            "    paths: ['docs/**', '*.html', '*.css']",
            "",
            "permissions:",
            "  contents: read",
            "  pages: write",
            "  id-token: write",
            "",
            "jobs:",
            "  deploy:",
            "    runs-on: ubuntu-latest",
            "    environment:",
            "      name: github-pages",
            "      url: ${{ steps.deployment.outputs.page_url }}",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - name: Setup Pages",
            "        uses: actions/configure-pages@v4",
            "      - name: Upload artifact",
            "        uses: actions/upload-pages-artifact@v3",
            "        with:",
            "          path: docs/",
            "      - name: Deploy to GitHub Pages",
            "        id: deployment",
            "        uses: actions/deploy-pages@v4",
            "```",
        ]),
    },
    {
        "filename": "scheduled_data_fetch.md",
        "title": "Scheduled Data Fetch (Cron)",
        "content": "\n".join([
            "# Scheduled Data Fetch via GitHub Actions Cron",
            "",
            "Fetch data on a schedule and commit updates.",
            "",
            "```yaml",
            "name: Scheduled Data Fetch",
            "on:",
            "  schedule:",
            "    - cron: '0 */6 * * *'  # Every 6 hours",
            "  workflow_dispatch: {}",
            "",
            "jobs:",
            "  fetch:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - uses: actions/setup-python@v5",
            "        with:",
            "          python-version: '3.12'",
            "      - name: Fetch data",
            "        run: python scripts/fetch_data.py",
            "      - name: Commit if changed",
            "        run: |",
            "          git config user.name 'github-actions[bot]'",
            "          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'",
            "          git add data/",
            "          git diff --staged --quiet || git commit -m 'chore: update data [skip ci]'",
            "          git push",
            "```",
        ]),
    },
    {
        "filename": "issue_responder.md",
        "title": "Auto Issue Responder",
        "content": "\n".join([
            "# Auto Issue Responder",
            "",
            "Automatically label and greet new issues.",
            "",
            "```yaml",
            "name: Issue Responder",
            "on:",
            "  issues:",
            "    types: [opened]",
            "",
            "jobs:",
            "  respond:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "      - name: Label issue",
            "        uses: actions/github-script@v7",
            "        with:",
            "          script: |",
            "            const title = context.payload.issue.title.toLowerCase();",
            "            const labels = [];",
            "            if (title.includes('bug')) labels.push('bug');",
            "            if (title.includes('feature')) labels.push('enhancement');",
            "            if (title.includes('docs')) labels.push('documentation');",
            "            if (labels.length === 0) labels.push('triage');",
            "            await github.rest.issues.addLabels({",
            "              owner: context.repo.owner,",
            "              repo: context.repo.repo,",
            "              issue_number: context.issue.number,",
            "              labels: labels",
            "            });",
            "      - name: Welcome comment",
            "        uses: actions/github-script@v7",
            "        with:",
            "          script: |",
            "            await github.rest.issues.createComment({",
            "              owner: context.repo.owner,",
            "              repo: context.repo.repo,",
            "              issue_number: context.issue.number,",
            "              body: 'Thanks for opening this issue! We will review it shortly.'",
            "            });",
            "```",
        ]),
    },
    {
        "filename": "badge_generator.md",
        "title": "Dynamic Badge Generator",
        "content": "\n".join([
            "# Dynamic Badge Generator",
            "",
            "Generate and update repo badges from code metrics.",
            "",
            "```yaml",
            "name: Update Badges",
            "on:",
            "  push:",
            "    branches: [main]",
            "",
            "jobs:",
            "  badges:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - uses: actions/setup-python@v5",
            "        with:",
            "          python-version: '3.12'",
            "      - name: Count engines",
            "        id: count",
            "        run: |",
            "          COUNT=$(ls mycelium/*.py | wc -l)",
            "          echo \"engine_count=$COUNT\" >> $GITHUB_OUTPUT",
            "      - name: Create badge",
            "        uses: schneegans/dynamic-badges-action@v1.7.0",
            "        with:",
            "          auth: ${{ secrets.GIST_TOKEN }}",
            "          gistID: YOUR_GIST_ID",
            "          filename: engines.json",
            "          label: engines",
            "          message: ${{ steps.count.outputs.engine_count }}",
            "          color: brightgreen",
            "```",
        ]),
    },
    {
        "filename": "release_drafter.md",
        "title": "Automated Release Drafter",
        "content": "\n".join([
            "# Automated Release Drafter",
            "",
            "Auto-draft releases from merged PRs.",
            "",
            "```yaml",
            "name: Release Drafter",
            "on:",
            "  push:",
            "    branches: [main]",
            "  pull_request:",
            "    types: [opened, reopened, synchronize]",
            "",
            "permissions:",
            "  contents: read",
            "  pull-requests: write",
            "",
            "jobs:",
            "  update_release_draft:",
            "    runs-on: ubuntu-latest",
            "    permissions:",
            "      contents: write",
            "      pull-requests: write",
            "    steps:",
            "      - uses: release-drafter/release-drafter@v6",
            "        env:",
            "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
            "```",
            "",
            "Create `.github/release-drafter.yml`:",
            "```yaml",
            "name-template: 'v$RESOLVED_VERSION'",
            "tag-template: 'v$RESOLVED_VERSION'",
            "categories:",
            "  - title: 'Features'",
            "    labels: ['enhancement']",
            "  - title: 'Bug Fixes'",
            "    labels: ['bug']",
            "change-template: '- $TITLE @$AUTHOR (#$NUMBER)'",
            "template: |",
            "  ## Changes",
            "  $CHANGES",
            "```",
        ]),
    },
    {
        "filename": "stale_issue_closer.md",
        "title": "Stale Issue Auto-Closer",
        "content": "\n".join([
            "# Stale Issue Auto-Closer",
            "",
            "Close issues and PRs that have been inactive.",
            "",
            "```yaml",
            "name: Close Stale Issues",
            "on:",
            "  schedule:",
            "    - cron: '0 0 * * *'  # Daily at midnight",
            "",
            "jobs:",
            "  stale:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "      - uses: actions/stale@v9",
            "        with:",
            "          stale-issue-message: 'This issue has been inactive for 30 days. Closing soon.'",
            "          stale-pr-message: 'This PR has been inactive for 14 days. Please update.'",
            "          days-before-issue-stale: 30",
            "          days-before-pr-stale: 14",
            "          days-before-issue-close: 7",
            "          days-before-pr-close: 7",
            "          stale-issue-label: 'stale'",
            "          stale-pr-label: 'stale'",
            "```",
        ]),
    },
    {
        "filename": "security_scan.md",
        "title": "Security Dependency Scan",
        "content": "\n".join([
            "# Security Dependency Scan",
            "",
            "Scan dependencies for known vulnerabilities on every PR.",
            "",
            "```yaml",
            "name: Security Scan",
            "on:",
            "  pull_request:",
            "    branches: [main]",
            "  schedule:",
            "    - cron: '0 8 * * 1'  # Monday 8am",
            "",
            "jobs:",
            "  audit:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - uses: actions/setup-python@v5",
            "        with:",
            "          python-version: '3.12'",
            "      - name: Install and audit",
            "        run: |",
            "          pip install pip-audit safety",
            "          pip-audit --strict || true",
            "          safety check --full-report || true",
            "      - name: Check for secrets",
            "        uses: trufflesecurity/trufflehog@main",
            "        with:",
            "          extra_args: --only-verified",
            "```",
        ]),
    },
]

AI_PROMPTS_TEMPLATES = [
    {
        "filename": "system_prompt_assistant.md",
        "title": "General-Purpose System Prompt",
        "content": "\n".join([
            "# General-Purpose System Prompt",
            "",
            "A structured system prompt for AI assistants.",
            "",
            "```",
            "You are a helpful, precise, and thoughtful assistant.",
            "",
            "## Core Behaviors",
            "- Answer directly and concisely",
            "- When uncertain, say so explicitly",
            "- Break complex problems into clear steps",
            "- Cite sources when making factual claims",
            "",
            "## Response Format",
            "- Use markdown for structure",
            "- Code blocks with language tags",
            "- Bullet points for lists of 3+ items",
            "- Tables for comparative data",
            "",
            "## Constraints",
            "- Never fabricate URLs, citations, or statistics",
            "- If a task is ambiguous, ask one clarifying question before proceeding",
            "- Maximum response length: 2000 words unless explicitly asked for more",
            "```",
        ]),
    },
    {
        "filename": "chain_of_thought.md",
        "title": "Chain-of-Thought Reasoning Template",
        "content": "\n".join([
            "# Chain-of-Thought Reasoning Template",
            "",
            "Force step-by-step reasoning for complex problems.",
            "",
            "```",
            "Solve the following problem step by step.",
            "",
            "## Process",
            "1. UNDERSTAND: Restate the problem in your own words",
            "2. PLAN: List the steps needed to solve it",
            "3. EXECUTE: Work through each step, showing your reasoning",
            "4. VERIFY: Check your answer against the original question",
            "5. ANSWER: State the final answer clearly",
            "",
            "## Rules",
            "- Show all intermediate calculations",
            "- If you hit a dead end, backtrack and explain why",
            "- Label each step clearly",
            "- If assumptions are needed, state them explicitly",
            "",
            "Problem: [INSERT PROBLEM HERE]",
            "```",
        ]),
    },
    {
        "filename": "json_output_enforcer.md",
        "title": "JSON Output Enforcer Prompt",
        "content": "\n".join([
            "# JSON Output Enforcer Prompt",
            "",
            "Force the model to output valid JSON every time.",
            "",
            "```",
            "You must respond ONLY with valid JSON. No markdown, no explanation, no preamble.",
            "",
            "Output Schema:",
            "{",
            '  "status": "success" | "error",',
            '  "data": {',
            '    "result": "<your analysis>",',
            '    "confidence": 0.0-1.0,',
            '    "reasoning": "<brief explanation>"',
            "  },",
            '  "metadata": {',
            '    "model": "<model name>",',
            '    "timestamp": "<ISO 8601>"',
            "  }",
            "}",
            "",
            "Rules:",
            "- All string values must be properly escaped",
            "- Numbers must not be quoted",
            "- No trailing commas",
            "- No comments in the JSON",
            "- If you cannot answer, set status to error and explain in data.result",
            "```",
        ]),
    },
    {
        "filename": "code_generator.md",
        "title": "Code Generation Prompt Template",
        "content": "\n".join([
            "# Code Generation Prompt Template",
            "",
            "Structured prompt for generating production-quality code.",
            "",
            "```",
            "Generate code for the following task.",
            "",
            "## Requirements",
            "- Language: [LANGUAGE]",
            "- Framework: [FRAMEWORK or 'none']",
            "- Purpose: [DESCRIPTION]",
            "",
            "## Code Standards",
            "- Include type hints/annotations where the language supports them",
            "- Add docstrings to all public functions",
            "- Handle errors with try/except (do not silently swallow errors)",
            "- Use meaningful variable names (no single letters except loop vars)",
            "- Follow PEP 8 (Python) / standard style guide for the language",
            "",
            "## Output Format",
            "1. Brief description of the approach (2-3 sentences)",
            "2. The complete, runnable code",
            "3. Example usage showing expected input and output",
            "4. Known limitations or edge cases",
            "",
            "## Constraints",
            "- Prefer standard library over third-party packages",
            "- Code must be self-contained (no external config files required)",
            "- Include a __main__ block for direct execution",
            "```",
        ]),
    },
    {
        "filename": "data_analyst.md",
        "title": "Data Analysis System Prompt",
        "content": "\n".join([
            "# Data Analysis System Prompt",
            "",
            "Prompt for structured data analysis tasks.",
            "",
            "```",
            "You are a data analyst. Analyze the provided data following this process:",
            "",
            "## Analysis Steps",
            "1. DATA SUMMARY: Describe shape, types, and basic statistics",
            "2. QUALITY CHECK: Identify missing values, outliers, and inconsistencies",
            "3. PATTERNS: Find trends, correlations, and clusters",
            "4. INSIGHTS: List 3-5 actionable insights",
            "5. VISUALIZATION: Suggest appropriate chart types for key findings",
            "",
            "## Output Format",
            "Always structure your response as:",
            "- Executive Summary (2-3 sentences)",
            "- Key Findings (bulleted list)",
            "- Detailed Analysis (sections per step above)",
            "- Recommendations (numbered list)",
            "",
            "## Rules",
            "- Use exact numbers, not vague qualifiers",
            "- Show your calculations",
            "- Distinguish correlation from causation",
            "- Flag any data quality issues before drawing conclusions",
            "```",
        ]),
    },
    {
        "filename": "persona_template.md",
        "title": "Persona-Based Prompt Template",
        "content": "\n".join([
            "# Persona-Based Prompt Template",
            "",
            "Define a specific expert persona for the AI.",
            "",
            "```",
            "You are [ROLE], a [EXPERIENCE]-year veteran in [DOMAIN].",
            "",
            "## Background",
            "- Specialization: [SPECIALTY]",
            "- Key skills: [SKILL_1], [SKILL_2], [SKILL_3]",
            "- Communication style: [STYLE - e.g., direct, academic, casual]",
            "",
            "## Behavior Guidelines",
            "- Prioritize practical, tested solutions over theoretical ones",
            "- When asked about areas outside your expertise, redirect clearly",
            "- Use industry-standard terminology but explain jargon when first used",
            "- Provide examples from real-world scenarios",
            "",
            "## Response Pattern",
            "1. Acknowledge the question",
            "2. Provide your expert analysis",
            "3. Offer a concrete recommendation",
            "4. Note any caveats or edge cases",
            "```",
        ]),
    },
    {
        "filename": "few_shot_template.md",
        "title": "Few-Shot Learning Template",
        "content": "\n".join([
            "# Few-Shot Learning Template",
            "",
            "Provide examples so the model learns the pattern.",
            "",
            "```",
            "Classify the following text into one of these categories:",
            "[CATEGORY_1], [CATEGORY_2], [CATEGORY_3]",
            "",
            "## Examples",
            "",
            "Input: [EXAMPLE_1_INPUT]",
            "Category: [EXAMPLE_1_CATEGORY]",
            "Reasoning: [EXAMPLE_1_REASONING]",
            "",
            "Input: [EXAMPLE_2_INPUT]",
            "Category: [EXAMPLE_2_CATEGORY]",
            "Reasoning: [EXAMPLE_2_REASONING]",
            "",
            "Input: [EXAMPLE_3_INPUT]",
            "Category: [EXAMPLE_3_CATEGORY]",
            "Reasoning: [EXAMPLE_3_REASONING]",
            "",
            "---",
            "Now classify this text:",
            "Input: [USER_INPUT]",
            "Category:",
            "Reasoning:",
            "```",
        ]),
    },
    {
        "filename": "output_parser.md",
        "title": "Structured Output Parser Prompt",
        "content": "\n".join([
            "# Structured Output Parser Prompt",
            "",
            "Extract structured data from unstructured text.",
            "",
            "```",
            "Extract the following fields from the text below.",
            "Return ONLY a JSON object with these fields:",
            "",
            "Required fields:",
            '  "name": string,',
            '  "date": string (ISO 8601),',
            '  "amount": number,',
            '  "category": string (one of: income, expense, transfer),',
            '  "notes": string (empty string if not found)',
            "",
            "Rules:",
            "- If a field cannot be determined, use null",
            "- Dates should be normalized to YYYY-MM-DD format",
            "- Amounts should be numeric (no currency symbols)",
            "- Category must be one of the specified values",
            "",
            "Text to parse:",
            "[INSERT TEXT HERE]",
            "```",
        ]),
    },
]

SOLARPUNK_CONFIGS_TEMPLATES = [
    {
        "filename": "engine_template.md",
        "title": "SolarPunk Engine Template",
        "content": "\n".join([
            "# SolarPunk Engine Template",
            "",
            "Boilerplate for creating a new engine in the nerve center.",
            "",
            "```python",
            "# NEURAL_LINK: The",
            "# Part of the Meeko SolarPunk Swarm.",
            "",
            "import json",
            "from pathlib import Path",
            "from datetime import datetime, timezone",
            "",
            "BASE = Path(__file__).resolve().parent.parent",
            "DATA = BASE / 'data'",
            "DATA.mkdir(exist_ok=True)",
            "",
            "STATE_FILE = DATA / 'ENGINE_NAME_state.json'",
            "",
            "def load_json(path):",
            "    try:",
            "        return json.loads(Path(path).read_text(encoding='utf-8'))",
            "    except Exception:",
            "        return {}",
            "",
            "def save_json(path, data):",
            "    Path(path).write_text(",
            "        json.dumps(data, indent=2, ensure_ascii=False), encoding='utf-8'",
            "    )",
            "",
            "def run():",
            "    print('[ENGINE_NAME] Starting...')",
            "    state = load_json(STATE_FILE)",
            "    # -- your logic here --",
            "    state['last_run'] = datetime.now(timezone.utc).isoformat()",
            "    save_json(STATE_FILE, state)",
            "    print('[ENGINE_NAME] Complete.')",
            "",
            "if __name__ == '__main__':",
            "    run()",
            "```",
        ]),
    },
    {
        "filename": "omnibus_config.md",
        "title": "OMNIBUS Configuration Template",
        "content": "\n".join([
            "# OMNIBUS Configuration Template",
            "",
            "How to add engines to the OMNIBUS orchestrator.",
            "",
            "```json",
            "{",
            '  "omnibus_version": 30,',
            '  "engine_groups": {',
            '    "revenue": {',
            '      "engines": [',
            '        "PRODUCT_FORGE",',
            '        "GUMROAD_DEPLOYER",',
            '        "AFFILIATE_MAXIMIZER"',
            "      ],",
            '      "run_order": "sequential",',
            '      "fail_mode": "continue"',
            "    },",
            '    "content": {',
            '      "engines": [',
            '        "ARTICLE_WRITER",',
            '        "DEVTO_PUBLISHER",',
            '        "TWEET_WRITER"',
            "      ],",
            '      "run_order": "sequential",',
            '      "fail_mode": "continue"',
            "    },",
            '    "infrastructure": {',
            '      "engines": [',
            '        "AUTO_HEALER",',
            '        "TOPOLOGY_MAPPER",',
            '        "SELF_WIRING_ENGINE"',
            "      ],",
            '      "run_order": "parallel",',
            '      "fail_mode": "log_and_continue"',
            "    }",
            "  },",
            '  "schedule": "*/30 * * * *",',
            '  "notifications": true',
            "}",
            "```",
        ]),
    },
    {
        "filename": "bridge_pattern.md",
        "title": "Engine Bridge Pattern",
        "content": "\n".join([
            "# Engine Bridge Pattern",
            "",
            "Connect two engines via shared JSON state files.",
            "",
            "```python",
            "# Bridge: ENGINE_A -> shared_state.json -> ENGINE_B",
            "",
            "import json",
            "from pathlib import Path",
            "from datetime import datetime, timezone",
            "",
            "DATA = Path(__file__).resolve().parent.parent / 'data'",
            "",
            "class Bridge:",
            "    def __init__(self, source_engine, dest_engine, state_file):",
            "        self.source = source_engine",
            "        self.dest = dest_engine",
            "        self.state_path = DATA / state_file",
            "",
            "    def emit(self, payload):",
            "        state = {",
            "            'source': self.source,",
            "            'dest': self.dest,",
            "            'timestamp': datetime.now(timezone.utc).isoformat(),",
            "            'payload': payload,",
            "            'consumed': False,",
            "        }",
            "        self.state_path.write_text(",
            "            json.dumps(state, indent=2), encoding='utf-8'",
            "        )",
            "",
            "    def consume(self):",
            "        if not self.state_path.exists():",
            "            return None",
            "        state = json.loads(self.state_path.read_text(encoding='utf-8'))",
            "        if state.get('consumed'):",
            "            return None",
            "        state['consumed'] = True",
            "        self.state_path.write_text(",
            "            json.dumps(state, indent=2), encoding='utf-8'",
            "        )",
            "        return state['payload']",
            "",
            "# Usage:",
            "# producer: Bridge('SCRAPER', 'ANALYZER', 'scraper_bridge.json').emit({'urls': [...]})",
            "# consumer: data = Bridge('SCRAPER', 'ANALYZER', 'scraper_bridge.json').consume()",
            "```",
        ]),
    },
    {
        "filename": "wire_pattern.md",
        "title": "Engine Wire Pattern (Topology)",
        "content": "\n".join([
            "# Engine Wire Pattern (Topology)",
            "",
            "Define typed connections between engines in the mesh.",
            "",
            "```python",
            "# Wire definition for TOPOLOGY_MAPPER",
            "",
            "WIRE_DEFINITIONS = [",
            "    {",
            "        'source': 'PRODUCT_FORGE',",
            "        'target': 'GUMROAD_DEPLOYER',",
            "        'wire_type': 'data_flow',",
            "        'shared_file': 'product_forge_report.json',",
            "        'description': 'New products trigger deployment',",
            "    },",
            "    {",
            "        'source': 'ARTICLE_WRITER',",
            "        'target': 'DEVTO_PUBLISHER',",
            "        'wire_type': 'data_flow',",
            "        'shared_file': 'article_drafts.json',",
            "        'description': 'Written articles get published',",
            "    },",
            "    {",
            "        'source': 'AUTO_HEALER',",
            "        'target': 'TOPOLOGY_MAPPER',",
            "        'wire_type': 'health_check',",
            "        'shared_file': 'auto_healer_report.json',",
            "        'description': 'Health status feeds topology view',",
            "    },",
            "]",
            "",
            "# Wire types: data_flow, health_check, trigger, feedback_loop",
            "# Each wire is bidirectional-aware but flows in one direction.",
            "```",
        ]),
    },
    {
        "filename": "cortex_directive.md",
        "title": "Cortex Directive Config",
        "content": "\n".join([
            "# Cortex Directive Configuration",
            "",
            "The central command structure for the nerve center.",
            "",
            "```json",
            "{",
            '  "directive": "maximize_revenue_and_reach",',
            '  "priority_engines": [',
            '    "PRODUCT_FORGE",',
            '    "GUMROAD_DEPLOYER",',
            '    "DEVTO_PUBLISHER"',
            "  ],",
            '  "constraints": {',
            '    "max_api_calls_per_hour": 100,',
            '    "max_git_commits_per_cycle": 5,',
            '    "require_dry_run_first": true',
            "  },",
            '  "flags": {',
            '    "enable_auto_publish": false,',
            '    "enable_auto_deploy": false,',
            '    "enable_revenue_tracking": true',
            "  },",
            '  "version": "2026-04-04"',
            "}",
            "```",
        ]),
    },
    {
        "filename": "event_bus.md",
        "title": "Event Bus Pattern",
        "content": "\n".join([
            "# Event Bus Pattern",
            "",
            "Lightweight event system for engine-to-engine communication.",
            "",
            "```python",
            "import json",
            "from pathlib import Path",
            "from datetime import datetime, timezone",
            "",
            "DATA = Path(__file__).resolve().parent.parent / 'data'",
            "EVENT_LOG = DATA / 'event_bus_log.json'",
            "",
            "def emit_event(source, event_type, payload=None):",
            "    log = []",
            "    if EVENT_LOG.exists():",
            "        try:",
            "            log = json.loads(EVENT_LOG.read_text(encoding='utf-8'))",
            "        except Exception:",
            "            log = []",
            "    event = {",
            "        'source': source,",
            "        'type': event_type,",
            "        'payload': payload or {},",
            "        'timestamp': datetime.now(timezone.utc).isoformat(),",
            "        'consumed_by': [],",
            "    }",
            "    log.append(event)",
            "    # Keep last 100 events",
            "    log = log[-100:]",
            "    EVENT_LOG.write_text(json.dumps(log, indent=2), encoding='utf-8')",
            "    return event",
            "",
            "def poll_events(consumer, event_type=None, limit=10):",
            "    if not EVENT_LOG.exists():",
            "        return []",
            "    log = json.loads(EVENT_LOG.read_text(encoding='utf-8'))",
            "    results = []",
            "    for evt in reversed(log):",
            "        if consumer in evt.get('consumed_by', []):",
            "            continue",
            "        if event_type and evt['type'] != event_type:",
            "            continue",
            "        results.append(evt)",
            "        if len(results) >= limit:",
            "            break",
            "    return results",
            "```",
        ]),
    },
    {
        "filename": "health_check.md",
        "title": "Engine Health Check Pattern",
        "content": "\n".join([
            "# Engine Health Check Pattern",
            "",
            "Standard health verification for any engine.",
            "",
            "```python",
            "import json, importlib, sys",
            "from pathlib import Path",
            "from datetime import datetime, timezone",
            "",
            "def check_engine_health(engine_path):",
            "    results = {",
            "        'engine': engine_path.stem,",
            "        'timestamp': datetime.now(timezone.utc).isoformat(),",
            "        'checks': {},",
            "    }",
            "    # 1. File exists",
            "    results['checks']['exists'] = engine_path.exists()",
            "",
            "    # 2. Syntax valid",
            "    try:",
            "        compile(engine_path.read_text(encoding='utf-8'), str(engine_path), 'exec')",
            "        results['checks']['syntax'] = True",
            "    except SyntaxError as e:",
            "        results['checks']['syntax'] = str(e)",
            "",
            "    # 3. Has run() function",
            "    text = engine_path.read_text(encoding='utf-8')",
            "    results['checks']['has_run'] = 'def run(' in text",
            "",
            "    # 4. Has main guard",
            "    results['checks']['has_main'] = \"__name__\" in text and \"__main__\" in text",
            "",
            "    # Overall",
            "    checks = results['checks']",
            "    results['healthy'] = all(",
            "        v is True for v in checks.values()",
            "    )",
            "    return results",
            "```",
        ]),
    },
    {
        "filename": "state_machine.md",
        "title": "Engine State Machine Pattern",
        "content": "\n".join([
            "# Engine State Machine Pattern",
            "",
            "Track engine lifecycle through defined states.",
            "",
            "```python",
            "import json",
            "from pathlib import Path",
            "from datetime import datetime, timezone",
            "",
            "STATES = ['idle', 'running', 'success', 'error', 'cooldown']",
            "TRANSITIONS = {",
            "    'idle': ['running'],",
            "    'running': ['success', 'error'],",
            "    'success': ['idle', 'cooldown'],",
            "    'error': ['idle'],",
            "    'cooldown': ['idle'],",
            "}",
            "",
            "class EngineState:",
            "    def __init__(self, engine_name, state_dir):",
            "        self.name = engine_name",
            "        self.path = Path(state_dir) / ('%s_lifecycle.json' % engine_name.lower())",
            "        self.state = 'idle'",
            "        self.history = []",
            "",
            "    def transition(self, new_state):",
            "        if new_state not in TRANSITIONS.get(self.state, []):",
            "            raise ValueError(",
            "                'Invalid transition: %s -> %s' % (self.state, new_state)",
            "            )",
            "        self.history.append({",
            "            'from': self.state,",
            "            'to': new_state,",
            "            'at': datetime.now(timezone.utc).isoformat(),",
            "        })",
            "        self.state = new_state",
            "        self._save()",
            "",
            "    def _save(self):",
            "        data = {",
            "            'engine': self.name,",
            "            'current_state': self.state,",
            "            'history': self.history[-20:],",
            "        }",
            "        self.path.write_text(json.dumps(data, indent=2), encoding='utf-8')",
            "```",
        ]),
    },
]

DOMAIN_TEMPLATES = {
    "python-automation": PYTHON_AUTOMATION_TEMPLATES,
    "github-actions": GITHUB_ACTIONS_TEMPLATES,
    "ai-prompts": AI_PROMPTS_TEMPLATES,
    "solarpunk-configs": SOLARPUNK_CONFIGS_TEMPLATES,
}


def generate_domain(domain_name, templates):
    """Generate all template files for a single domain."""
    domain_dir = PRODUCTS / domain_name
    domain_dir.mkdir(parents=True, exist_ok=True)

    manifest_entries = []
    files_written = 0

    for tmpl in templates:
        filepath = domain_dir / tmpl["filename"]
        filepath.write_text(tmpl["content"], encoding="utf-8")
        files_written += 1
        manifest_entries.append({
            "filename": tmpl["filename"],
            "title": tmpl["title"],
            "size_bytes": filepath.stat().st_size,
        })
        print("  [+] %s/%s" % (domain_name, tmpl["filename"]))

    # Write manifest
    manifest = {
        "domain": domain_name,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "template_count": len(manifest_entries),
        "templates": manifest_entries,
    }
    manifest_path = domain_dir / "manifest.json"
    save_json(manifest_path, manifest)
    print("  [manifest] %s/manifest.json (%d templates)" % (domain_name, len(manifest_entries)))

    return {
        "domain": domain_name,
        "files_written": files_written,
        "manifest_path": str(manifest_path),
    }


def run():
    """Generate micro digital products across all domains."""
    print("[MICRO_PRODUCT_FACTORY] Starting product generation...")
    print("=" * 60)

    report = {
        "engine": "MICRO_PRODUCT_FACTORY",
        "started_at": datetime.now(timezone.utc).isoformat(),
        "domains": {},
        "total_files": 0,
        "total_domains": 0,
    }

    for domain_name, templates in DOMAIN_TEMPLATES.items():
        print("\n[Domain: %s] Generating %d templates..." % (domain_name, len(templates)))
        result = generate_domain(domain_name, templates)
        report["domains"][domain_name] = result
        report["total_files"] += result["files_written"]
        report["total_domains"] += 1

    report["completed_at"] = datetime.now(timezone.utc).isoformat()
    try: _h=json.loads((DATA/"homeostasis_state.json").read_text(encoding="utf-8"))
    except: _h={}
    try: _c=json.loads((DATA/"neural_cortex_state.json").read_text(encoding="utf-8"))
    except: _c={}
    report["nervous_system"]={"equilibrium":_h.get("equilibrium",0),"trend":_h.get("trend","unknown"),"brain_confidence":_c.get("decision_confidence",0)}
    save_json(REPORT_FILE, report)

    print("\n" + "=" * 60)
    print("[MICRO_PRODUCT_FACTORY] Complete!")
    print("  Total domains:  %d" % report["total_domains"])
    print("  Total files:    %d" % report["total_files"])
    print("  Report:         %s" % REPORT_FILE)


if __name__ == "__main__":
    run()
