# NEURAL_LINK: The
# Part of the Meeko SolarPunk Swarm.

#!/usr/bin/env python3
"""
PASSIVE_INCOME_ARCHITECT.py — SolarPunk's passive income invention engine
=========================================================================
This engine does NOT repeat itself. Every cycle it:

  1. Inventories ACTUAL live capabilities (what secrets exist, what APIs work)
  2. Cross-joins them to find unexploited income combos
  3. Scores each idea by: friction_to_launch × recurring_potential × passive_score
  4. Picks the TOP 3 highest-value lowest-friction streams not yet built
  5. Writes detailed build specs to data/passive_income_streams.json
  6. Creates a GitHub Issue with the action plan
  7. Actually starts bootstrapping the SIMPLEST one via SELF_BUILDER queue

Ideas are generated by Groq AI using the actual current capability map as context.
This engine won't repeat ideas it already queued — it checks the history.

Current capability inventory:
  HOSTING:  GitHub Pages (free, unlimited static)
  PAYMENTS: PayPal.me (zero-fee links), Ko-fi (shop), Gumroad (listings)
  AI:       Groq (llama3-70b free), HuggingFace inference, Ollama local
  PUBLISH:  Bluesky, DEV.to, GitHub Issues/Pages, Gmail broadcast
  STORAGE:  GitHub repo (free, git-backed), GitHub Releases (file hosting)
  COMPUTE:  GitHub Actions (2000 min/month free), Python 3.x
  DATA:     SERPAPI (search), web scraping
  REVENUE:  Email Agent Exchange (pay-per-task AI agents)

Passive income = something that earns while SolarPunk runs without Meeko touching it.
"""
import os, json, urllib.request, urllib.error, urllib.parse
from pathlib import Path
from datetime import datetime, timezone

DATA = Path("data"); DATA.mkdir(exist_ok=True)
GROQ_KEY   = os.environ.get("GROQ_API_KEY", "")
GH_TOKEN   = os.environ.get("GITHUB_TOKEN", "")
GH_REPO    = "meekotharaccoon-cell/meeko-nerve-center"
BASE       = "https://meekotharaccoon-cell.github.io/meeko-nerve-center"

# ── Hardcoded capability map (updated manually when new secrets added) ──────────
CAPABILITY_MAP = {
    "groq":          bool(os.environ.get("GROQ_API_KEY")),
    "openrouter":    bool(os.environ.get("OPENROUTER_KEY")),
    "anthropic":     bool(os.environ.get("os.getenv("os.getenv("ANTHROPIC_API_KEY")")", "").strip()),
    "huggingface":   bool(os.environ.get("HF_TOKEN")),
    "github":        bool(os.environ.get("GITHUB_TOKEN")),
    "gmail":         bool(os.environ.get("GMAIL_APP_PASSWORD")),
    "bluesky":       bool(os.environ.get("BLUESKY_APP_PASSWORD")),
    "devto":         bool(os.environ.get("DEVTO_API_KEY")),
    "gumroad":       bool(os.environ.get("GUMROAD_SECRET")),
    "paypal_direct": True,   # paypal.me needs no secret
    "kofi":          True,   # ko-fi.com/meekotharaccoon exists
    "github_pages":  True,   # always available with the repo
    "github_actions": True,
    "github_releases": True,
    "serpapi":       bool(os.environ.get("SERPAPI_KEY")),
    "ollama_local":  False,  # local only
    "paypal_api":    bool(os.environ.get("PAYPAL_CLIENT_ID")),
}

# ── Ideas already in the system (avoid re-generating) ────────────────────────
BOOTSTRAP_IDEAS = {
    "email_agent_exchange": "Pay-per-task AI email agents — already built",
    "gumroad_guides": "PDF guides on Gumroad — already built",
    "kofi_shop": "Ko-fi digital products — built",
    "github_releases_hosting": "Free file hosting via GitHub Releases — built",
    "nanoshop_widget": "Embeddable 1-click shop widget — just built",
    "bluesky_promotions": "Bluesky product announcements — built",
    "devto_seo": "DEV.to articles driving shop traffic — built",
    "gaza_art_gallery": "Gaza Rose digital art prints — built",
    "proof_ledger": "Public donation transparency — built",
}

def rj(fname, fb=None):
    f = DATA / fname
    if f.exists():
        try: return json.loads(f.read_text())
        except: pass
    return fb if fb is not None else {}


def load_state():
    return rj("passive_income_state.json", {
        "cycles": 0,
        "ideas_generated": 0,
        "ideas_built": 0,
        "all_ideas": {},
        "queued_for_build": [],
        "issues_created": [],
    })


def active_capabilities():
    return [k for k, v in CAPABILITY_MAP.items() if v]


def groq_generate(prompt):
    if not GROQ_KEY:
        return ""
    try:
        req = urllib.request.Request(
            "https://api.groq.com/openai/v1/chat/completions",
            data=json.dumps({
                "model": "llama3-70b-8192",
                "max_tokens": 2000,
                "temperature": 0.9,
                "messages": [{"role": "user", "content": prompt}]
            }).encode(),
            headers={"Authorization": f"Bearer {GROQ_KEY}",
                     "Content-Type": "application/json"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=45) as r:
            return json.loads(r.read())["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"  Groq error: {e}")
        return ""


def invent_income_streams(caps, already_built):
    """Ask Groq to invent new passive income streams using real capabilities."""
    cap_str = ", ".join(caps)
    built_str = "\n".join(f"- {k}: {v}" for k, v in list(already_built.items())[:8])

    prompt = f"""You are SolarPunk, an autonomous AI revenue system. You have these REAL capabilities right now:
{cap_str}

You have already built these income streams (DO NOT repeat them):
{built_str}

Invent 8 NEW passive income streams that:
1. Use ONLY the capabilities listed above
2. Are 100% passive after setup (no human needed)
3. Are genuinely new (not variations of what's built)
4. Generate recurring or growing income
5. Can be fully automated with Python + the listed APIs
6. Some should take <2 hours to build (high speed); some can be bigger ideas

For each stream, output a JSON object like this (output ONLY a JSON array, no markdown):
[
  {{
    "id": "snake_case_unique_id",
    "name": "Short catchy name",
    "description": "1-2 sentences on what it is and how it earns",
    "capabilities_used": ["groq", "github_pages", "paypal_direct"],
    "how_it_earns": "Specific mechanism — who pays, how much, how often",
    "build_time_hours": 2,
    "passive_score": 9,
    "monthly_potential_usd": 25,
    "friction_to_launch": 2,
    "first_action": "Exactly what to build first (one sentence)",
    "engine_name": "SNAKE_CASE_ENGINE_NAME",
    "gaza_pct": 15
  }},
  ...
]

Ideas MUST be creative and genuinely different. Think: link-in-bio micropayment pages, 
AI-generated content subscriptions, affiliate link automation, GitHub Sponsors tiers,
embeddable widgets for other sites, AI prompt marketplaces, generated image feeds,
RSS-to-newsletter monetization, automated grant applications, API reselling, 
GitHub Sponsors perks automation, tip jars embedded in DEV.to articles, etc.
Output ONLY the JSON array."""

    raw = groq_generate(prompt)
    if not raw:
        return []

    # Extract JSON array
    try:
        # Find first [ and last ]
        start = raw.find("[")
        end   = raw.rfind("]") + 1
        if start == -1 or end == 0:
            return []
        ideas = json.loads(raw[start:end])
        return [i for i in ideas if isinstance(i, dict) and i.get("id")]
    except:
        return []


def score_idea(idea):
    """Score = passive_score * monthly_potential / (friction * build_time^0.5)"""
    try:
        p = float(idea.get("passive_score", 5))
        m = float(idea.get("monthly_potential_usd", 10))
        f = max(1, float(idea.get("friction_to_launch", 5)))
        b = max(1, float(idea.get("build_time_hours", 8)))
        return round((p * m) / (f * (b ** 0.5)), 2)
    except:
        return 0


def create_github_issue(title, body):
    if not GH_TOKEN:
        return None
    try:
        req = urllib.request.Request(
            f"https://api.github.com/repos/{GH_REPO}/issues",
            data=json.dumps({"title": title, "body": body, "labels": ["passive-income", "build"]}).encode(),
            headers={"Authorization": f"token {GH_TOKEN}",
                     "Content-Type": "application/json",
                     "User-Agent": "SolarPunk/1.0"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read())["number"]
    except Exception as e:
        print(f"  Issue create error: {e}")
        return None


def queue_for_self_builder(engine_name, spec):
    """Add to SELF_BUILDER queue so it gets built next cycle."""
    qf = DATA / "self_builder_queue.json"
    queue = []
    if qf.exists():
        try: queue = json.loads(qf.read_text())
        except: pass
    if not isinstance(queue, list): queue = []

    # Don't add duplicates
    existing_names = [q.get("engine_name") for q in queue]
    if engine_name in existing_names:
        return False

    queue.append({
        "engine_name": engine_name,
        "spec": spec,
        "queued_at": datetime.now(timezone.utc).isoformat(),
        "priority": "high",
        "source": "PASSIVE_INCOME_ARCHITECT",
    })
    qf.write_text(json.dumps(queue, indent=2))
    return True


def run():
    ts = datetime.now(timezone.utc).isoformat()
    print(f"\nPASSIVE_INCOME_ARCHITECT — {ts}")

    state = load_state()
    state["cycles"] = state.get("cycles", 0) + 1

    caps = active_capabilities()
    print(f"  Live capabilities: {len(caps)} → {', '.join(caps[:8])}...")

    # Load already-known ideas
    all_ideas = state.get("all_ideas", {})
    queued    = state.get("queued_for_build", [])

    # Don't reinvent if we already have enough unbuilt ideas
    unbuilt = [iid for iid, idea in all_ideas.items()
               if idea.get("status") in ("pending", "queued")]
    if len(unbuilt) >= 5:
        print(f"  {len(unbuilt)} ideas already pending — skipping invention")
    else:
        print(f"  Inventing new passive income streams via Groq...")
        already_built = {**BOOTSTRAP_IDEAS, **{
            iid: idea.get("name", iid)
            for iid, idea in all_ideas.items()
            if idea.get("status") == "built"
        }}
        new_ideas = invent_income_streams(caps, already_built)
        print(f"  Groq returned {len(new_ideas)} ideas")

        for idea in new_ideas:
            iid = idea["id"]
            if iid in all_ideas or iid in already_built:
                continue
            idea["score"]      = score_idea(idea)
            idea["status"]     = "pending"
            idea["invented_at"]= ts
            all_ideas[iid]     = idea
            state["ideas_generated"] = state.get("ideas_generated", 0) + 1

    # Pick top 3 by score to queue for building
    pending = sorted(
        [(iid, idea) for iid, idea in all_ideas.items() if idea.get("status") == "pending"],
        key=lambda x: x[1].get("score", 0), reverse=True
    )

    newly_queued = []
    for iid, idea in pending[:3]:
        engine_name = idea.get("engine_name", f"{iid.upper()}_ENGINE")
        ok = queue_for_self_builder(engine_name, idea)
        if ok:
            all_ideas[iid]["status"] = "queued"
            queued.append(iid)
            newly_queued.append(iid)
            print(f"  → Queued for build: {engine_name} (score:{idea.get('score')}, ${idea.get('monthly_potential_usd')}/mo)")

    # Create a GitHub Issue with the full plan
    if newly_queued and GH_TOKEN:
        top_ideas = [all_ideas[iid] for iid in newly_queued]
        issue_body = "## 💡 New Passive Income Streams — Auto-Generated\n\n"
        issue_body += f"Capabilities available: `{', '.join(caps[:10])}`\n\n"
        for idea in top_ideas:
            issue_body += f"### {idea.get('name', idea['id'])}\n"
            issue_body += f"**Engine:** `{idea.get('engine_name', 'TBD')}`  \n"
            issue_body += f"**How it earns:** {idea.get('how_it_earns', '')}  \n"
            issue_body += f"**Monthly potential:** ${idea.get('monthly_potential_usd', '?')}  \n"
            issue_body += f"**Build time:** {idea.get('build_time_hours', '?')} hrs  \n"
            issue_body += f"**Passive score:** {idea.get('passive_score', '?')}/10  \n"
            issue_body += f"**First action:** {idea.get('first_action', '')}  \n"
            issue_body += f"**Gaza %:** {idea.get('gaza_pct', 15)}%  \n\n"
        issue_body += f"\n*Generated by PASSIVE_INCOME_ARCHITECT at {ts}*  \n"
        issue_body += f"*SELF_BUILDER will build these in the next cycle.*"

        inum = create_github_issue(
            f"[PIA] {len(top_ideas)} new passive income streams queued for build",
            issue_body
        )
        if inum:
            state["issues_created"] = state.get("issues_created", []) + [inum]
            print(f"  ✓ GitHub Issue #{inum} created")

    # Write full idea catalog for humans to read
    catalog = sorted(all_ideas.values(), key=lambda x: x.get("score", 0), reverse=True)
    (DATA / "passive_income_catalog.json").write_text(json.dumps({
        "updated": ts,
        "total_ideas": len(catalog),
        "pending": sum(1 for i in catalog if i.get("status") == "pending"),
        "queued": sum(1 for i in catalog if i.get("status") == "queued"),
        "built": sum(1 for i in catalog if i.get("status") == "built"),
        "ideas": catalog,
    }, indent=2))

    state["all_ideas"] = all_ideas
    state["queued_for_build"] = queued
    (DATA / "passive_income_state.json").write_text(json.dumps(state, indent=2))

    print(f"  Done: {len(all_ideas)} ideas total | {len(newly_queued)} newly queued | {sum(1 for i in all_ideas.values() if i.get('status')=='built')} built")
    return state


if __name__ == "__main__":
    run()
