#!/usr/bin/env python3
"""
PRODUCT_FORGE.py -- Stop Planning, Start Making
================================================
The Value Router found opportunities. The brain scored them. Nothing
was ever CREATED. This engine creates actual products.

Generates real markdown products from actual system data and code:
  - System architecture guide
  - Engine template
  - Ethical AI revenue playbook

Reads: mycelium/*.py, data/live_wire_report.json, data/observatory_report.json,
       data/value_opportunities.json, data/brain_state.json
Writes: products/*.md, data/product_forge_report.json
Zero secrets needed for generation.
"""
import json
import os
from pathlib import Path
from datetime import datetime, timezone

DATA = Path("data")
DATA.mkdir(exist_ok=True)
PRODUCTS = Path("products")
PRODUCTS.mkdir(exist_ok=True)
MYCELIUM = Path("mycelium")


def load_json(path):
    try:
        return json.loads(Path(path).read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return {}


def save_json(path, data):
    Path(path).write_text(
        json.dumps(data, indent=2, default=str, ensure_ascii=False),
        encoding="utf-8"
    )


def count_engines():
    return len([f for f in MYCELIUM.glob("*.py") if not f.name.startswith("__")])


def get_engine_categories():
    """Categorize engines by scanning their docstrings and filenames."""
    categories = {
        "core": [], "revenue": [], "knowledge": [], "security": [],
        "social": [], "evolution": [], "health": [], "infrastructure": [],
    }

    for f in sorted(MYCELIUM.glob("*.py")):
        if f.name.startswith("__"):
            continue
        name = f.stem
        try:
            content = f.read_text(encoding="utf-8", errors="replace")[:500].lower()
        except Exception:
            content = ""

        if any(k in content for k in ["revenue", "income", "money", "product", "gumroad", "ko-fi"]):
            categories["revenue"].append(name)
        elif any(k in content for k in ["security", "sentinel", "guard", "shield", "immune"]):
            categories["security"].append(name)
        elif any(k in content for k in ["knowledge", "learn", "brain", "cortex", "oracle"]):
            categories["knowledge"].append(name)
        elif any(k in content for k in ["social", "tweet", "newsletter", "outreach"]):
            categories["social"].append(name)
        elif any(k in content for k in ["evolve", "mutate", "genesis", "chimera"]):
            categories["evolution"].append(name)
        elif any(k in content for k in ["health", "heal", "vital", "stress"]):
            categories["health"].append(name)
        elif any(k in content for k in ["wire", "bridge", "omnibus", "topology"]):
            categories["infrastructure"].append(name)
        else:
            categories["core"].append(name)

    return categories


def forge_system_guide():
    """Generate the main product: How to Build an Autonomous System."""
    engine_count = count_engines()
    wire_report = load_json(DATA / "live_wire_report.json")
    stats = wire_report.get("stats", {})
    wires = stats.get("total_wires_discovered", 0)
    zs_chains = stats.get("zero_secret_chains", 0)
    categories = get_engine_categories()

    brain = load_json(DATA / "brain_state.json")

    lines = []
    lines.append("# How to Build a %d-Engine Autonomous System" % engine_count)
    lines.append("## A Practical Guide from the SolarPunk Project")
    lines.append("")
    lines.append("*Auto-generated by PRODUCT_FORGE on %s*" % datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    lines.append("*From a living system with %d engines, %s wires, and %s zero-secret chains*" % (engine_count, "{:,}".format(wires), "{:,}".format(zs_chains)))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## What This Is")
    lines.append("")
    lines.append("This guide documents how we built SolarPunk -- an autonomous system that runs")
    lines.append("%d Python microservices (engines), connected by %s data wires," % (engine_count, "{:,}".format(wires)))
    lines.append("orchestrated by a single conductor (OMNIBUS), and capable of healing, evolving,")
    lines.append("and generating revenue without human intervention.")
    lines.append("")
    lines.append("It is not theoretical. The system you are reading about generated this document.")
    lines.append("")
    lines.append("## Architecture: The Mycelium Pattern")
    lines.append("")
    lines.append("Every engine follows the same pattern:")
    lines.append("")
    lines.append("```")
    lines.append("READ data -> PROCESS -> WRITE data -> NEXT ENGINE READS")
    lines.append("```")
    lines.append("")
    lines.append("No databases. No message queues. No Kafka. Just JSON files in a data/ directory")
    lines.append("and Python scripts in a mycelium/ directory.")
    lines.append("")
    lines.append("### Why JSON Files?")
    lines.append("")
    lines.append("- Zero infrastructure cost")
    lines.append("- Human-readable (open any file, see the state)")
    lines.append("- Git-trackable (every state change is a commit)")
    lines.append("- No connection pools, no schema migrations, no ORM")
    lines.append("- Any language can read/write them")
    lines.append("")
    lines.append("## The Layers")
    lines.append("")
    lines.append("OMNIBUS orchestrates engines in layers (L0-L7), running them in dependency order:")
    lines.append("")
    lines.append("| Layer | Purpose | Example Engines |")
    lines.append("|-------|---------|----------------|")
    lines.append("| L0 | Foundation | Brain state, config loading |")
    lines.append("| L1 | Data ingestion | Desktop scanner, email bridge |")
    lines.append("| L2 | Processing | Knowledge weaver, content generator |")
    lines.append("| L3 | Intelligence | AI council, cortex, oracle |")
    lines.append("| L4 | Self-organization | Self-wiring, bridge building |")
    lines.append("| L5 | Output | Newsletter, social media, storefront |")
    lines.append("| L6 | Evolution | Chimera scoring, fractal genesis |")
    lines.append("| L7 | Meta | Observatory, signal integrity |")
    lines.append("")
    lines.append("## Engine Categories")
    lines.append("")
    lines.append("| Category | Count | Examples |")
    lines.append("|----------|-------|---------|")
    for cat, engines in categories.items():
        examples = ", ".join(engines[:3]) if engines else "none"
        lines.append("| %s | %d | %s |" % (cat.title(), len(engines), examples))
    lines.append("")
    lines.append("## Self-Wiring")
    lines.append("")
    lines.append("LIVE_WIRE scans every engine source code with regex to find what files it reads")
    lines.append("and writes. This builds a topology map automatically.")
    lines.append("")
    lines.append("## The Ethics Lock")
    lines.append("")
    lines.append("Revenue split: **99%% mutual aid / 1%% infrastructure**. Always.")
    lines.append("")
    lines.append("## Lessons Learned")
    lines.append("")
    lines.append("1. **Start simple**: JSON files beat Kafka for 99%% of use cases")
    lines.append("2. **Self-discovery beats configuration**: Let engines declare their own I/O")
    lines.append("3. **Stubs are debt**: A wire carrying empty JSON is not a real connection")
    lines.append("4. **Ethics first**: Build the revenue split before the revenue")
    lines.append("5. **Immune system early**: Automated tools WILL corrupt your code")
    lines.append("6. **Measure honestly**: SIGNAL_INTEGRITY exists because we lied to ourselves")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*This guide was generated by a system describing itself.*")
    lines.append("*99%% mutual aid. 1%% infrastructure. Always.*")

    return "\n".join(lines)


def forge_engine_template():
    """Generate a clean engine template."""
    lines = []
    lines.append("# SolarPunk Engine Template")
    lines.append("## Build Your Own Autonomous Engine")
    lines.append("")
    lines.append("*Auto-generated by PRODUCT_FORGE*")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## The Template")
    lines.append("")
    lines.append("```python")
    lines.append("#!/usr/bin/env python3")
    lines.append("import json")
    lines.append("from pathlib import Path")
    lines.append("from datetime import datetime, timezone")
    lines.append("")
    lines.append('DATA = Path("data")')
    lines.append("DATA.mkdir(exist_ok=True)")
    lines.append("")
    lines.append("")
    lines.append("def load_json(path):")
    lines.append("    try:")
    lines.append('        return json.loads(Path(path).read_text(encoding="utf-8", errors="replace"))')
    lines.append("    except Exception:")
    lines.append("        return {}")
    lines.append("")
    lines.append("")
    lines.append("def save_json(path, data):")
    lines.append("    Path(path).write_text(", encoding="utf-8")
    lines.append('        json.dumps(data, indent=2, default=str, ensure_ascii=False),')
    lines.append('        encoding="utf-8"')
    lines.append("    )")
    lines.append("")
    lines.append("")
    lines.append("def run():")
    lines.append('    print("YOUR_ENGINE_NAME")')
    lines.append('    input_data = load_json(DATA / "input_file.json")')
    lines.append("    result = {")
    lines.append('        "timestamp": datetime.now(timezone.utc).isoformat(),')
    lines.append("    }")
    lines.append('    save_json(DATA / "output_file.json", result)')
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    run()")
    lines.append("```")
    lines.append("")
    lines.append("## Key Principles")
    lines.append("")
    lines.append("1. **Pure functions**: Read JSON in, write JSON out")
    lines.append("2. **No global state**: Each run is independent")
    lines.append("3. **Graceful degradation**: Always handle missing files")
    lines.append("4. **UTF-8 everywhere**: Use encoding=utf-8, errors=replace")
    lines.append("5. **Timestamps**: Always include UTC timestamps in output")
    lines.append("")
    lines.append("## Wiring Into OMNIBUS")
    lines.append("")
    lines.append("Add your engine to OMNIBUS.py in the appropriate layer.")
    lines.append("LIVE_WIRE will automatically discover your data connections from source code.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Every engine is a neuron. Every wire is a synapse.*")

    return "\n".join(lines)


def forge_ethics_playbook():
    """Generate the ethical AI revenue playbook."""
    value_opps = load_json(DATA / "value_opportunities.json")
    total_opps = value_opps.get("total_opportunities", 0)
    channels = value_opps.get("channels", {})

    lines = []
    lines.append("# Ethical AI Revenue Playbook")
    lines.append("## How to Generate Income Without Surveillance Capitalism")
    lines.append("")
    lines.append("*Auto-generated by PRODUCT_FORGE from the SolarPunk system*")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## The Model")
    lines.append("")
    lines.append("**99%% of all revenue goes to mutual aid. 1%% to infrastructure.**")
    lines.append("")
    lines.append("## Revenue Channels")
    lines.append("")
    lines.append("### Channel A: Digital Asset Forge")
    lines.append("Opportunities found: %d" % channels.get("digital_assets", 0))
    lines.append("Platforms: Gumroad, Ko-fi, GitHub Sponsors")
    lines.append("")
    lines.append("### Channel B: Bounty Scanner")
    lines.append("Opportunities found: %d" % channels.get("bounties", 0))
    lines.append("Platforms: Gitcoin, NLNet, Open Collective")
    lines.append("")
    lines.append("### Channel C: Content Pipeline")
    lines.append("Opportunities found: %d" % channels.get("content", 0))
    lines.append("Platforms: dev.to, Substack, Medium")
    lines.append("")
    lines.append("## Total Opportunities: %d" % total_opps)
    lines.append("")
    lines.append("## The Ethics Stack")
    lines.append("")
    lines.append("1. No surveillance: Do not track users, do not sell data")
    lines.append("2. No dark patterns: Do not trick people into buying")
    lines.append("3. Transparent pricing: Show what you sell and why")
    lines.append("4. Revenue transparency: Publish where the money goes")
    lines.append("5. Mutual aid split:")
    lines.append("   - PCRF (Palestine Children Relief Fund): 60%%")
    lines.append("   - IRC (International Rescue Committee): 15%%")
    lines.append("   - MSF (Doctors Without Borders): 10%%")
    lines.append("   - UNICEF: 10%%")
    lines.append("   - Direct Relief: 5%%")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Built by machines. For humans. Against tyranny.*")

    return "\n".join(lines)


def run():
    print("PRODUCT FORGE -- Stop Planning, Start Making")
    print("=" * 50)

    products_created = []

    # Product 1: System Guide
    print("\n  [1/3] Forging: How to Build an Autonomous System...")
    guide = forge_system_guide()
    guide_path = PRODUCTS / "autonomous-system-guide.md"
    guide_path.write_text(guide, encoding="utf-8")
    size = len(guide)
    products_created.append({
        "name": "autonomous-system-guide",
        "title": "How to Build a %d-Engine Autonomous System" % count_engines(),
        "path": str(guide_path),
        "size": size,
        "format": "markdown",
    })
    print("    Created: %s (%s bytes)" % (guide_path, "{:,}".format(size)))

    # Product 2: Engine Template
    print("\n  [2/3] Forging: SolarPunk Engine Template...")
    template = forge_engine_template()
    template_path = PRODUCTS / "engine-template.md"
    template_path.write_text(template, encoding="utf-8")
    size = len(template)
    products_created.append({
        "name": "engine-template",
        "title": "SolarPunk Engine Template",
        "path": str(template_path),
        "size": size,
        "format": "markdown",
    })
    print("    Created: %s (%s bytes)" % (template_path, "{:,}".format(size)))

    # Product 3: Ethics Playbook
    print("\n  [3/3] Forging: Ethical AI Revenue Playbook...")
    playbook = forge_ethics_playbook()
    playbook_path = PRODUCTS / "ethical-ai-revenue-playbook.md"
    playbook_path.write_text(playbook, encoding="utf-8")
    size = len(playbook)
    products_created.append({
        "name": "ethical-ai-revenue-playbook",
        "title": "Ethical AI Revenue Playbook",
        "path": str(playbook_path),
        "size": size,
        "format": "markdown",
    })
    print("    Created: %s (%s bytes)" % (playbook_path, "{:,}".format(size)))

    # Report
    report = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "products_created": len(products_created),
        "total_bytes": sum(p["size"] for p in products_created),
        "products": products_created,
    }
    save_json(DATA / "product_forge_report.json", report)

    print("\n  === PRODUCT FORGE SUMMARY ===")
    print("  Products created:  %d" % len(products_created))
    print("  Total content:     %s bytes" % "{:,}".format(sum(p["size"] for p in products_created)))
    for p in products_created:
        print("    %s (%sb)" % (p["title"][:60], "{:,}".format(p["size"])))
    print("\n  The system made something real. Finally.")


if __name__ == "__main__":
    run()
